// ===================== game state & simulation =====================
let ART,LS,MAPS={},M=null,P=null,T=0,TIME=.71,state='intro',uid=1,hitstop=0,shake=0,bossActive=null;
const mobs=[],bots=[],npcs=[],loots=[],projs=[],teles=[],fx=[],texts=[],traps=[],respawnQ=[],timers=[];
const weather={rain:.7,target:.7,t:150};
const later=(t,fn)=>timers.push({t,fn});const zones=[];const ELC={poison:['#d8ff8a','#7ad83a','#3a8a2a'],blood:['#ff9aaa','#e0405e','#8a1a2a'],shadow:['#e8c8ff','#a46ae0','#4a2a6a'],fire:['#fff0a0','#ff8a2a','#c8301a'],frost:['#ffffff','#bfe8ff','#5ab0e0'],storm:['#ffffff','#bfe8ff','#7ab8ff']};
const ELSL={poison:'#9ae85a',blood:'#ff6a84',shadow:'#b88aff',fire:'#ffb04a',frost:'#cfeeff',storm:'#9ad8ff'};
function wElem(p){const b=p.eq&&p.eq.arma&&BASES[p.eq.arma.id];return (b?(b.fire?'fire':b.frost?'frost':b.storm?'storm':null):null)||clsEl(p)}
function aElem(p){const b=p.eq&&p.eq.escudo&&BASES[p.eq.escudo.id];return b&&b.arrow||(p.evo==='cac'&&p.qel)||(p.cls==='a'?clsEl(p):null)}
function elemO(el,o){if(el)o.el=el;if(el==='poison')o.poison=1;else if(el==='fire')o.burn=1;else if(el==='frost'){o.slow=Math.max(o.slow||0,2);if(Math.random()<.15)o.freeze=1.6}else if(el==='storm')o.shock=1;return o}
function elemBurst(el,x,y,n=8){if(!el)return;const [wx,wy]=wpx(x,y),c=ELC[el];for(let i=0;i<n;i++){const a=Math.random()*6.283,s=rnd(15,el==='storm'?110:55);fx.push({type:'px',x:wx+rnd(-4,4),y:wy-12+rnd(-6,6),vx:Math.cos(a)*s,vy:el==='fire'?rnd(-60,-20):Math.sin(a)*s*.6-(el==='frost'?30:10),g:el==='fire'?-20:el==='frost'?160:0,t:0,life:rnd(.3,.7),col:pick(c),glow:1,sz:el==='frost'?2:1})}}
function arcTrail(el,x,y,a,r,arc){if(!el)return;for(let i=0;i<14;i++){const aa=a-arc/2+arc*i/13,rr=r*rnd(.7,1);const [wx,wy]=wpx(x+Math.cos(aa)*rr,y+Math.sin(aa)*rr);fx.push({type:'px',x:wx,y:wy-12,vx:rnd(-8,8),vy:el==='fire'?rnd(-45,-15):rnd(-15,15),g:el==='frost'?60:0,t:0,life:rnd(.3,.6),col:pick(ELC[el]),glow:1})}}
function dust(x,y,n=8,col='#8a7a62'){const [wx,wy]=wpx(x,y);for(let i=0;i<n;i++)fx.push({type:'smoke',x:wx+rnd(-10,10),y:wy+rnd(-4,4),t:0,life:rnd(.5,.9),vx:rnd(-14,14),col,sm:1})}
const skKeys=p=>['Q','E','R','T','Z','X','G'].filter(k=>skillSet(p)[k]);function zap(x,y){fx.push({type:'zap',x,y,t:0,life:.28,seed:Math.random()*999});for(let i=0;i<10;i++)fx.push({type:'p',x,y,vx:rnd(-3,3),vy:rnd(-3,3),t:0,life:.3,col:pick(['#ffffff','#bfe8ff','#7ab8ff']),tile:1,up:4})}
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const sunLevel=()=>.5-.5*Math.cos(Math.PI*2*TIME);
const nightF=()=>M&&M.indoor?0:clamp((.42-sunLevel())/.3,0,1);
const isNight=()=>sunLevel()<.3;
const safeAt=(m,x,y)=>(m.id==='world'&&x>=12&&x<31&&y>=12&&y<31)||(!!m.safeR&&x>=m.safeR[0]&&x<m.safeR[2]&&y>=m.safeR[1]&&y<m.safeR[3]);
const rainNow=()=>{const c=M&&M.climate;return c==='desert'||c==='snow'?0:c==='jungle'?Math.max(.22,weather.rain):weather.rain};
function homeMap(){const cur=MAPS[P.map];if(cur&&cur.temple&&cur.city)return P.map;if(cur&&cur.parent&&MAPS[cur.parent])return cur.parent;return'world'}
function travelTo(c){if(P.gold<TRAVEL_COST){toast('Ouro insuficiente',`A viagem custa ${TRAVEL_COST} ouro`);sfx('no');return}P.gold-=TRAVEL_COST;burstAt(P.x,P.y,0xa46ae0,30,70);sfx('blink');changeMap(c.map,c.at[0],c.at[1]);burstAt(P.x,P.y,0xbfe8ff,30,70);log(`O portal te leva até ${c.n}. ${c.d}`,'sys');toast(c.n,MAPS[c.map].name);uiDirty=1}
function walkable(m,x,y,mob){return inb(m,x,y)&&!m.solid[y*m.w+x]&&!(mob&&safeAt(m,x+.5,y+.5))}
function tryMove(m,e,dx,dy){const r=e.r||.3;const bl=(x,y)=>solidAt(m,x-r,y-r)||solidAt(m,x+r,y-r)||solidAt(m,x-r,y+r)||solidAt(m,x+r,y+r)||(e.type==='mob'&&safeAt(m,x,y));let moved=false;if(dx&&!bl(e.x+dx,e.y)){e.x+=dx;moved=true}if(dy&&!bl(e.x,e.y+dy)){e.y+=dy;moved=true}return moved}
function los(m,a,b){const d=Math.hypot(b.x-a.x,b.y-a.y),n=Math.ceil(d/.3);for(let i=1;i<n;i++){const t=i/n;if(solidAt(m,a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t))return false}return true}
function findPath(m,sx,sy,tx,ty,mob){sx|=0;sy|=0;tx|=0;ty|=0;
  if(!walkable(m,tx,ty,mob)){let best=null,bd=1e9;for(let r=1;r<=3&&!best;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const x=tx+dx,y=ty+dy;if(walkable(m,x,y,mob)){const d=Math.hypot(dx,dy);if(d<bd){bd=d;best=[x,y]}}}if(!best)return[];tx=best[0];ty=best[1]}
  if(sx===tx&&sy===ty)return[[tx+.5,ty+.5]];const W=m.w,N=W*m.h,g=new Float32Array(N).fill(1e9),from=new Int32Array(N).fill(-1),cl=new Uint8Array(N),hp=[];
  const push=(i,f)=>{hp.push([f,i]);let k=hp.length-1;while(k>0){const p=(k-1)>>1;if(hp[p][0]<=hp[k][0])break;[hp[p],hp[k]]=[hp[k],hp[p]];k=p}};
  const pop=()=>{const top=hp[0],l=hp.pop();if(hp.length){hp[0]=l;let k=0;for(;;){const a=2*k+1,b=a+1;let mm=k;if(a<hp.length&&hp[a][0]<hp[mm][0])mm=a;if(b<hp.length&&hp[b][0]<hp[mm][0])mm=b;if(mm===k)break;[hp[mm],hp[k]]=[hp[k],hp[mm]];k=mm}}return top};
  const s=sy*W+sx,goal=ty*W+tx;g[s]=0;push(s,0);let n=0;
  while(hp.length&&n++<4000){const i=pop()[1];if(i===goal)break;if(cl[i])continue;cl[i]=1;const x=i%W,y=(i/W)|0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(!walkable(m,nx,ny,mob))continue;if(dx&&dy&&(!walkable(m,x+dx,y,mob)||!walkable(m,x,y+dy,mob)))continue;const j=ny*W+nx,ng=g[i]+(dx&&dy?1.414:1);if(ng<g[j]){g[j]=ng;from[j]=i;const hx=Math.abs(nx-tx),hy=Math.abs(ny-ty);push(j,ng+Math.max(hx,hy)+.414*Math.min(hx,hy))}}}
  if(from[goal]<0)return[];const out=[];let c=goal;while(c!==s&&c>=0){out.push([c%W+.5,((c/W)|0)+.5]);c=from[c]}return out.reverse()}
function steer(e,tx,ty,spd,dt,mob){const m=MAPS[e.m||'world'];const d=Math.hypot(tx-e.x,ty-e.y);if(d<.05)return false;let gx=tx,gy=ty;
  if(!los(m,e,{x:tx,y:ty})){e.rp=(e.rp||0)-dt;if(e.rp<=0||!e.path||!e.path.length){e.path=findPath(m,e.x,e.y,tx,ty,mob);e.rp=.6}if(e.path&&e.path.length){if(Math.hypot(e.path[0][0]-e.x,e.path[0][1]-e.y)<.25)e.path.shift();if(e.path.length){gx=e.path[0][0];gy=e.path[0][1]}}}else e.path=[];
  const dx=gx-e.x,dy=gy-e.y,dl=Math.hypot(dx,dy)||1,st=Math.min(spd*dt,d);const mv=tryMove(m,e,dx/dl*st,dy/dl*st);e.d8=dir8(scrAng(dx,dy));e.moving=true;return mv}
// ---------- items ----------
function makeItem(id,r=0){const b=BASES[id];const it={id,uid:uid++};if(b.t!=='eq'){it.n=1;return it}if(b.u){it.r=4;it.aff=b.fix.map(a=>a.slice());return it}it.r=r;it.aff=(b.fix||[]).map(a=>a.slice());const pool=AFF_POOL.slice();for(let i=0;i<RAR[r].a;i++){const [a,lo,hi]=pool.splice(Math.floor(Math.random()*pool.length),1)[0];it.aff.push([a,rint(lo,hi)])}return it}
function rollRar(boost){boost=(boost||0)+(P&&P.buff&&P.buff.luck>0?.8:0);const x=Math.random();return x<.005+boost*.02?3:x<.04+boost*.07?2:x<.2+boost*.12?1:0}
function addItem(it,inv=P.inv){const b=BASES[it.id];if(b.t!=='eq'){for(let i=0;i<inv.length;i++)if(inv[i]&&inv[i].id===it.id&&inv[i].n<99){inv[i].n+=it.n||1;return true}}const i=inv.indexOf(null);if(i<0)return false;inv[i]=it;return true}
function countItem(id){return P.inv.reduce((s,it)=>s+(it&&it.id===id?(it.n||1):0),0)}
function takeItem(id,n=1){for(let i=0;i<P.inv.length&&n>0;i++){const it=P.inv[i];if(it&&it.id===id){const k=Math.min(n,it.n||1);n-=k;if(it.n)it.n-=k;if(!it.n||it.n<=0)P.inv[i]=null}}}
function itemName(it){return BASES[it.id].n+(it.up?' +'+it.up:'')}
function sellPrice(it){const b=BASES[it.id];if(b.t==='quest')return 0;if(b.sell)return b.sell;return Math.max(2,Math.round((b.buy||((b.atk||b.def||3)*12+b.lv*8))*.3*(1+(it.r||0)*.6)))}
// ---------- stats ----------
function D(p=P){const s={for:p.st.for,des:p.st.des,int:p.st.int,vit:p.st.vit},A={hp:0,mp:0,def:0,crit:0,aspd:0,speed:0,dmg:0,skill:0,vsBeast:0,vsGoblin:0,vsUndead:0,life:0,regen:0};let watk=0,edef=0;
  for(const k in p.eq){const it=p.eq[k];if(!it)continue;const b=BASES[it.id],m=RAR[it.r||0].m*(1+(it.up||0)*.07);if(b.atk)watk+=Math.round(b.atk*m);if(b.def)edef+=Math.round(b.def*m);for(const [a,v] of it.aff||[]){if(a in s)s[a]+=v;else A[a]=(A[a]||0)+v}}
  const c=CLASSES[p.cls],main=s[c.main],buff=p.buff&&p.buff.war>0,bless=p.buff&&p.buff.bless>0,eStr=p.buff&&p.buff.str>0,eSkin=p.buff&&p.buff.skin>0,ev=evoStat(p),ts=treeStat(p,{def:0,hp:1,crit:0,speed:1,dodge:0,mp:1});
  return{s,A,atk:Math.round((6+main*2.2+p.lv*1.3+watk)*(1+A.dmg/100)*(buff?1.25:1)*(eStr?1.2:1)*ev.atk),def:s.vit+edef+A.def+(buff?20:0)+(bless?25:0)+(eSkin?30:0)+ev.def+ts.def+(p.evo==='cav'?Math.round((s.vit+edef)*.15):0),maxHp:Math.round((60+s.vit*12+p.lv*14+c.hp+A.hp)*ts.hp),maxMp:Math.round((30+s.int*6+p.lv*4+A.mp)*ts.mp),crit:4+s.des*.45+A.crit+ts.crit,aspd:(1+s.des*.012+A.aspd/100)*ev.aspd,speed:CFG.moveSpeed*(1+A.speed/100)*ev.speed*ts.speed,dodge:Math.min(40,s.des*.35+ts.dodge)}}
// ---------- player ----------
const START={g:{arma:'esp_curta',escudo:'escudo_mad',peito:'armadura_rec',pernas:'grevas_rec',pes:'botas',maos:'luvas'},l:{arma:'adaga',escudo:'adaga_sec',cabeca:'capuz_assassino',peito:'gibao_sombra',pernas:'calcas',pes:'botas'},a:{arma:'arco_curto',escudo:'aljava',cabeca:'capuz',peito:'gibao',pernas:'calcas',pes:'botas'},m:{arma:'cajado',escudo:'tomo',cabeca:'chapeu',peito:'veste',pes:'botas'}};
function newPlayer(cfg){const p={type:'pc',id:uid++,name:cfg.name,cls:cfg.cls,skin:cfg.skin,hairC:cfg.hairC,hs:cfg.hs,capeC:cfg.capeC,beard:cfg.beard,lv:1,exp:0,pts:0,st:Object.assign({},CLASSES[cfg.cls].st),gold:25,inv:new Array(30).fill(null),eq:{},bank:{items:new Array(40).fill(null),gold:0},q:{filho:0,cacada:0,tumulo:0},flags:{chests:{},seen:{}},map:'world',x:21.5,y:24.6};
  for(const [sl,id] of Object.entries(START[cfg.cls]))p.eq[sl]=makeItem(id,0);
  const pi=(id,n)=>{const it=makeItem(id);it.n=n;p.inv[p.inv.indexOf(null)]=it};pi('pot_hp1',5);pi('pot_mp',3);pi('scroll',1);return hydrate(p)}
function hydrate(p){Object.assign(p,{type:'pc',r:.3,d8:0,anim:'idle',frame:0,animT:0,atkT:0,atkDur:.3,atkAnim:'atk',flash:0,kx:0,ky:0,ifr:0,stun:0,slowT:0,dash:null,cast:null,dead:false,deadT:0,cds:{atk:0,dash:0,Q:0,E:0,R:0,T:0,Z:0,X:0,G:0,pot:0},buff:{war:0,bless:0,str:0,skin:0,luck:0,lust:0},regT:0,combatT:0,moving:false,z:0});p.look=playerLook(p);const d=D(p);if(p.hp==null){p.hp=d.maxHp;p.mp=d.maxMp}return p}
function refreshLook(){P.look=playerLook(P)}
const input={keys:{},mx:0,my:0,mdown:false,joy:null,touch:false};
function aimPoint(){if(input.touch){const t=nearestMob(P,8);if(t)return[t.x,t.y];const a=P.lastMove||0;return[P.x+Math.cos(a)*3,P.y+Math.sin(a)*3]}const wx=input.mx*DPR/K+sx0,wy=input.my*DPR/K+sy0;return toTile(wx,wy)}
function aimA(){const [ax,ay]=aimPoint();return Math.atan2(ay-P.y,ax-P.x)}
function nearestMob(e,r){let b=null,bd=r;for(const m of mobs){if(m.m!==M.id||m.dying||m.dead||m.def.ai==='dummy')continue;const d=dist(e,m);if(d<bd){bd=d;b=m}}return b}
function moveInput(){let sx=0,sy=0;const k=input.keys;if(k.w||k.arrowup)sy-=1;if(k.s||k.arrowdown)sy+=1;if(k.a||k.arrowleft)sx-=1;if(k.d||k.arrowright)sx+=1;if(input.joy){sx=input.joy[0];sy=input.joy[1]}if(!sx&&!sy)return null;const dx=(sx/32+sy/16)/2,dy=(sy/16-sx/32)/2,l=Math.hypot(dx,dy);return[dx/l,dy/l,Math.min(1,Math.hypot(sx,sy))]}
function updPlayer(dt){const p=P;for(const k of ['str','skin','luck'])if(p.buff[k]>0)p.buff[k]=Math.max(0,p.buff[k]-dt);for(const k in p.cds)p.cds[k]=Math.max(0,p.cds[k]-dt);p.ifr-=dt;if(p.stealth>0){p.stealth-=dt;if(p.stealth<=0)addText(p,'Visível','#cfc6b8')}p.flash-=dt;p.buff.war-=dt;p.atkT-=dt;p.combatT-=dt;p.stun-=dt;p.slowT-=dt;
  if(p.dead){p.deadT+=dt;return}
  const d=D(p);p.hp=Math.min(p.hp,d.maxHp);p.mp=Math.min(p.mp,d.maxMp);
  p.regT+=dt;if(p.regT>=3){p.regT=0;const ooc=p.combatT<=0,safe=safeAt(M,p.x,p.y),rh=safe?CFG.regenSafe:ooc?CFG.regenOut:CFG.regenCombat;p.hp=Math.min(d.maxHp,p.hp+d.maxHp*rh+d.A.regen);p.mp=Math.min(d.maxMp,p.mp+d.maxMp*rh*1.6+p.st.int*.05)}
  if(p.spinT>0)p.spinT-=dt;
  if(p.buff.bless>0){p.buff.bless-=dt;p.hp=Math.min(d.maxHp,p.hp+d.maxHp*.02*dt)}
  for(let i=zones.length-1;i>=0;i--){const z=zones[i];z.t-=dt;z.tick-=dt;if(z.m!==M.id||z.t<=0){zones.splice(i,1);continue}if(z.vis){if(z.tick<=0){z.tick=.5;burstAt(z.x+rnd(-1.5,1.5),z.y+rnd(-1,1),0xfff0a0,4,20)}continue}if(z.tick<=0){z.tick=.5;if(Math.hypot(p.x-z.x,p.y-z.y)<z.r){const h=Math.round(d.maxHp*.04);p.hp=Math.min(d.maxHp,p.hp+h);addText(p,'+'+h,'#7fe08a')}for(const m of mobs)if(m.m===M.id&&!m.dying&&Math.hypot(m.x-z.x,m.y-z.y)<z.r+m.r)hitMob(m,.6,{skill:1,holy:1,quiet:1});burstAt(z.x+rnd(-1.5,1.5),z.y+rnd(-1,1),0xfff0a0,4,20)}}
  const mv=moveInput();
  if(p.cast){p.cast.t-=dt;if(mv||p.combatT>4.9){p.cast=null;addText(p,'Cancelado','#cfc6b8')}else if(p.cast.t<=0){p.cast=null;recall()}}
  if(p.dash){const ds=p.dash,st=Math.min(dt,ds.t);for(let i=0;i<3;i++)tryMove(M,p,ds.vx*st/3,ds.vy*st/3);ds.t-=dt;if(ds.hit)for(const m of mobs)if(m.m===M.id&&!m.dying&&!ds.hit.has(m.id)&&dist(m,p)<.9+m.r){ds.hit.add(m.id);if(ds.bleed){hitMob(m,1.4,{skill:1,melee:1});m.bleedT=4;m.bleedTick=.5}else{hitMob(m,1.2,elemO(wElem(p),{skill:1,stun:p.evo==='cav'?1.8:1.2,breakGuard:1,knock:3}));{const ka=Math.atan2(ds.vy,ds.vx);if(!m.def.boss&&blockedAt(M,m.x+Math.cos(ka)*1.3,m.y+Math.sin(ka)*1.3,.2)){m.stunT=Math.max(m.stunT||0,2.6);addText(m,'Contra a parede!','#ff8a6a',1);hitMob(m,.6,{skill:1,quiet:1});shake=Math.max(shake,.3)}}fx.push({type:'ring',x:m.x,y:m.y,r:1.3,t:0,life:.3,col:'#ffffff'});burstAt(m.x,m.y,0xffe8a0,14,90);elemBurst(wElem(p),m.x,m.y,10);shake=Math.max(shake,.25);hitstop=Math.max(hitstop,.06);sfx('block')}}
    if(ds.charge){ds.gt-=dt;if(ds.gt<=0){ds.gt=.035;ghostFx(p,'#ffcc5a');dust(p.x,p.y,2)}}
    if(Math.random()<.6)ghostFx(p);p.z=ds.leap?Math.sin((1-ds.t/ds.dur)*Math.PI)*14:0;if(ds.t<=0){p.dash=null;p.z=0}}
  else{const go=mv&&p.stun<=0,sp=go?d.speed*(p.atkT>0?.5:1)*(p.slowT>0?.5:1)*(p.stealth>0?1.3:1)*mv[2]:0,k=Math.min(1,dt*(go?11:16));p.vx=(p.vx||0)+((go?mv[0]*sp:0)-(p.vx||0))*k;p.vy=(p.vy||0)+((go?mv[1]*sp:0)-(p.vy||0))*k;const spd=Math.hypot(p.vx,p.vy);if(spd>.05){tryMove(M,p,p.vx*dt,p.vy*dt)}p.moving=spd>.6;if(go){p.lastMove=Math.atan2(mv[1],mv[0]);if(p.atkT<=0)p.d8=dir8(scrAng(mv[0],mv[1]))}}
  if(p.kx||p.ky){tryMove(M,p,p.kx*dt,p.ky*dt);const f=Math.pow(.002,dt);p.kx*=f;p.ky*=f;if(Math.abs(p.kx)+Math.abs(p.ky)<.05)p.kx=p.ky=0}
  if(input.mdown&&p.cds.atk<=0&&!p.dash&&p.stun<=0)basicAttack();
  if(p.atkT>0){const a=p.aimLock??aimA();p.d8=dir8(scrAng(Math.cos(a),Math.sin(a)))}
  // anim
  if(p.dash)p.anim='dash';else if(p.atkT>0){p.anim=p.atkAnim;p.frame=clamp(Math.floor((1-p.atkT/p.atkDur)*4),0,3)}else if(p.moving){p.anim='walk';p.animT+=dt*d.speed/CFG.moveSpeed;p.frame=Math.floor(p.animT*7.5)%8}else{p.anim='idle';p.frame=Math.floor(T*1.6)%2}
  // loot
  for(let i=loots.length-1;i>=0;i--){const l=loots[i];if(l.m!==M.id||l.age<.35)continue;if(dist(l,p)<.75){if(l.gold){p.gold+=l.gold;addText(p,`+${l.gold} ouro`,'#ffd860');sfx('coin');if(l.tomb)log(`Você recuperou ${l.gold} de ouro da sua lápide.`,'loot');loots.splice(i,1)}else if(addItem(l.item)){const r=l.item.r||0;log(`Você pegou: ${itemName(l.item)}${l.item.n>1?' x'+l.item.n:''}.`,'loot',r>0?RAR[r].c:null);sfx('pick');loots.splice(i,1);uiDirty=1}else if(!l.full){l.full=1;addText(p,'Inventário cheio','#ff8a7a')}}}
  // traps
  for(let i=traps.length-1;i>=0;i--){const t=traps[i];t.t-=dt;t.arm-=dt;if(t.t<=0){traps.splice(i,1);continue}if(t.arm>0)continue;for(const m of mobs)if(m.m===M.id&&!m.dying&&m.def.ai!=='dummy'&&dist(m,t)<.85){hitMob(m,2,{skill:1,root:2.5});burstAt(t.x,t.y,0xc8b090,14,40);sfx('trap');traps.splice(i,1);break}}
}
function basicAttack(){const p=P,d=D(p),sk=skillSet(p).atk,wb=p.eq.arma?BASES[p.eq.arma.id]:null,ws=wb&&wb.as||1;p.cds.atk=sk.cd*CFG.atkSlow/(d.aspd*ws);p.cast=null;const a=aimA();p.aimLock=a;
  if(p.cls==='g'&&wb&&wb.wt==='greatsword'){p.atkAnim='atk';p.atkDur=p.atkT=.62/Math.min(1.4,d.aspd);sfx('swing');later(.34,()=>{fx.push({type:'slash',x:p.x,y:p.y,a,r:2.1,t:0,life:.26,arc:2.4,heavy:1,col:'#cfeeff'});arcTrail('storm',p.x,p.y,a,2,2.4);const ix=p.x+Math.cos(a)*1.5,iy=p.y+Math.sin(a)*1.5;for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<2.3+m.r&&angDiff(Math.atan2(m.y-p.y,m.x-p.x),a)<1.25)hitMob(m,1,{melee:1,knock:2.2});zap(ix,iy);if(wb.storm)later(.12,()=>zap(ix+rnd(-.8,.8),iy+rnd(-.8,.8)));fx.push({type:'ring',x:ix,y:iy,r:2,t:0,life:.4,col:'#bfe8ff'});pokePlants(ix,iy,2);for(const m of mobs)if(m.m===M.id&&!m.dying&&Math.hypot(m.x-ix,m.y-iy)<2+m.r)hitMob(m,wb.storm?.85:.65,{shock:1,quiet:1});shake=Math.max(shake,.3);hitstop=Math.max(hitstop,.05);sfx('thunder');p.aimLock=null})}
  else if(p.cls==='g'){p.atkAnim='atk';p.atkDur=p.atkT=.3/Math.min(1.5,d.aspd);sfx('swing');const el=wElem(p);later(.08,()=>{fx.push({type:'slash',x:p.x,y:p.y,a,r:1.6,t:0,life:.18,arc:2,col:ELSL[el]});arcTrail(el,p.x,p.y,a,1.5,2);pokePlants(p.x+Math.cos(a)*1,p.y+Math.sin(a)*1,1);let any=false;for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<1.7+m.r&&angDiff(Math.atan2(m.y-p.y,m.x-p.x),a)<1.05){hitMob(m,1,elemO(el,{}));elemBurst(el,m.x,m.y,10);any=true}p.aimLock=null})}
  else if(p.cls==='a'){const xb=wb&&wb.wt==='crossbow';p.atkAnim='bow';p.atkDur=p.atkT=.3/Math.min(1.5,d.aspd);later(.12,()=>{shoot('p',p.x,p.y,a,xb?21:15,xb?'quarrel':'arrow',1,elemO(aElem(p),{pierce:xb?wb.pierce:0}));sfx(xb?'xbow':'bow');p.aimLock=null})}
  else if(p.cls==='l'&&wb&&wb.wt==='scythe'){p.atkAnim='atk';p.atkDur=p.atkT=.34/Math.min(1.6,d.aspd);sfx('swing');later(.12,()=>{fx.push({type:'slash',x:p.x,y:p.y,a,r:2,t:0,life:.26,arc:2.6,heavy:1,col:'#b88aff'});fx.push({type:'slash',x:p.x,y:p.y,a:a+.25,r:1.6,t:0,life:.22,arc:2.2,col:'#e8c8ff',dim:1});arcTrail('void',p.x,p.y,a,1.9,2.6);pokePlants(p.x+Math.cos(a)*1.2,p.y+Math.sin(a)*1.2,1.4);for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<2+m.r&&angDiff(Math.atan2(m.y-p.y,m.x-p.x),a)<1.3){hitMob(m,1,{melee:1,bleed:.3});elemBurst('shadow',m.x,m.y,6)}p.aimLock=null})}
  else if(p.cls==='l'){p.atkAnim='atk';p.atkDur=p.atkT=.22/Math.min(1.6,d.aspd);sfx('swing');p.altHand=!p.altHand;later(.06,()=>{fx.push({type:'slash',x:p.x,y:p.y,a:a+(p.altHand?.3:-.3),r:1.3,t:0,life:.14,arc:1.4,col:p.altHand?'#e8c8ff':'#a46aff'});arcTrail('void',p.x,p.y,a+(p.altHand?.3:-.3),1.2,1.4);pokePlants(p.x+Math.cos(a)*.9,p.y+Math.sin(a)*.9,.9);for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<1.45+m.r&&angDiff(Math.atan2(m.y-p.y,m.x-p.x),a)<.85){hitMob(m,.9,{melee:1,el:'void'});elemBurst('void',m.x,m.y,7);break}p.aimLock=null})}
  else{const hl=isHealer(p);p.atkAnim='cast';p.atkDur=p.atkT=.32/Math.min(1.5,d.aspd);later(.14,()=>{shoot('p',p.x,p.y,a,10.5,hl?'holy':'bolt',1,hl?{holy:1}:{});sfx(hl?'heal':'bolt');p.aimLock=null})}}
function doDash(){const p=P;if(p.dead||p.cds.dash>0||p.dash||p.stun>0)return;const mv=moveInput();const a=mv?Math.atan2(mv[1],mv[0]):aimA();const sp=CFG.dashDist/.18;p.dash={vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,t:.18,dur:.18};p.ifr=.26;p.cds.dash=CFG.dashCD;p.cast=null;sfx('dash');p.d8=dir8(scrAng(Math.cos(a),Math.sin(a)))}
function useSkill(k){const p=P;if(!p||p.dead)return;const sk=skillSet(p)[k];if(!sk)return;if(p.lv<sk.lv){toast(`${sk.n} libera no nível ${sk.lv}.`);return}if(p.cds[k]>0||p.stun>0)return;if(p.mp<sk.mp){addText(p,'Mana insuficiente','#8ab4ff');sfx('no');return}
  p.mp-=sk.mp;p.cds[k]=sk.cd*CFG.skillCD*cdMul();p.cast=null;p.spin=null;skillUsed(k);const a=aimA(),[ax,ay]=aimPoint(),d=D(p),code=skCode(p,k);netSkill(code,a,ax,ay);
  const ptAt=(maxD)=>{const dd=Math.min(maxD,Math.hypot(ax-p.x,ay-p.y));return[p.x+Math.cos(a)*dd,p.y+Math.sin(a)*dd]};
  if(evoSkill(code,k,p,a,ax,ay,ptAt,sk,d)){evoAfter(p,k,a,ax,ay);return}
  switch(code){
    case'gQ':{const el=wElem(p);p.atkAnim='atk';p.atkDur=p.atkT=.42;p.spinT=.42;sfx('whirl');fx.push({type:'whirl',x:p.x,y:p.y,r:2.1,t:0,life:.42,el});dust(p.x,p.y,10);later(.12,()=>{fx.push({type:'ring',x:p.x,y:p.y,r:2.3,t:0,life:.35,col:ELSL[el]||'#fff2d0'});pokePlants(p.x,p.y,2.1);arcTrail(el,p.x,p.y,0,2,6.28);for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<2.1+m.r){hitMob(m,1.6,elemO(el,{skill:1,knock:2}));elemBurst(el,m.x,m.y,8);burstAt(m.x,m.y,0xfff2d0,5,70)}});break}
    case'gE':{p.dash={vx:Math.cos(a)*16,vy:Math.sin(a)*16,t:.25,dur:.25,hit:new Set(),charge:1,gt:0};fx.push({type:'ring',x:p.x,y:p.y,r:1.2,t:0,life:.3,col:'#e8d8b0'});dust(p.x,p.y,8);p.ifr=.3;p.d8=dir8(scrAng(Math.cos(a),Math.sin(a)));sfx('dash');break}
    case'gR':p.buff.war=8;for(let i=0;i<3;i++)later(i*.12,()=>{fx.push({type:'ring',x:p.x,y:p.y,r:2.2+i*.9,t:0,life:.5,col:i===1?'#ff6a3a':'#ffcc5a'});shake=Math.max(shake,.12)});burstAt(p.x,p.y,0xffcc5a,26,110);dust(p.x,p.y,12);fx.push({type:'roar',x:p.x,y:p.y,t:0,life:.6});addText(p,'Grito de Guerra!','#ffcc5a',1);sfx('shout');break;
    case'gT':p.atkAnim='atk';p.atkDur=p.atkT=.48;p.aimLock=a;later(.3,()=>{const el=wElem(p);shake=Math.max(shake,.5);hitstop=Math.max(hitstop,.07);sfx('boom');fx.push({type:'slash',x:p.x,y:p.y,a,r:2.7,t:0,life:.3,arc:1.6,heavy:1,col:ELSL[el]});const segs=[];for(let c=0;c<6;c++){let ca=a+rnd(-.7,.7),cx=p.x+Math.cos(a)*.5,cy=p.y+Math.sin(a)*.5;const pts=[[cx,cy]];const L2=rnd(1.8,3.1);for(let s2=0;s2<6;s2++){ca+=rnd(-.45,.45);cx+=Math.cos(ca)*L2/6;cy+=Math.sin(ca)*L2/6;pts.push([cx,cy])}segs.push(pts)}fx.push({type:'crack',segs,t:0,life:1.6,el});const [wx0,wy0]=wpx(p.x+Math.cos(a)*1.4,p.y+Math.sin(a)*1.4);for(let i=0;i<18;i++)fx.push({type:'px',x:wx0+rnd(-20,20),y:wy0+rnd(-8,8),vx:rnd(-50,50),vy:rnd(-130,-60),g:320,t:0,life:rnd(.5,.9),col:pick(['#6a5a48','#8a7a62','#4a3e32']),sz:3});dust(p.x+Math.cos(a)*1.5,p.y+Math.sin(a)*1.5,14);if(el==='storm')zap(p.x+Math.cos(a)*2,p.y+Math.sin(a)*2);if(el)for(const sg of segs)for(const q of sg)elemBurst(el,q[0],q[1],1);for(let i=0;i<14;i++){const aa=a+rnd(-.8,.8),rr=rnd(.8,2.6);burstAt(p.x+Math.cos(aa)*rr,p.y+Math.sin(aa)*rr,0x9a8a6a,3,30)}for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<2.8+m.r&&angDiff(Math.atan2(m.y-p.y,m.x-p.x),a)<.85)hitMob(m,3,elemO(wElem(p),{skill:1,knock:6,breakGuard:1}));p.aimLock=null});break;
    case'aQ':p.atkAnim='bow';p.atkDur=p.atkT=.3;later(.1,()=>{for(const o of [-.26,0,.26])shoot('p',p.x,p.y,a+o,15,'arrow',.9,elemO(aElem(p),{skill:1}));sfx('bow')});break;
    case'aE':{const b=a+Math.PI;p.dash={vx:Math.cos(b)*3.6/.3,vy:Math.sin(b)*3.6/.3,t:.3,dur:.3,leap:1};p.ifr=.36;sfx('dash');break}
    case'aR':{if(traps.length>=2)traps.shift();traps.push({x:p.x,y:p.y,t:40,arm:.6});sfx('trap');break}
    case'aT':{const [tx,ty]=ptAt(7);teles.push({shape:'circle',x:tx,y:ty,r:2.2,t:0,dur:2.1,team:'p',col:'#ffe08a',tick:0});for(let i=0;i<6;i++)later(.3+i*.32,()=>{for(let j=0;j<6;j++){const aa=Math.random()*6.28,rr=Math.random()*2;fx.push({type:'arrowfall',x:tx+Math.cos(aa)*rr,y:ty+Math.sin(aa)*rr,t:0,life:.25})}pokePlants(tx,ty,2.2);for(const m of mobs)if(m.m===M.id&&!m.dying&&Math.hypot(m.x-tx,m.y-ty)<2.2+m.r)hitMob(m,.6,elemO(aElem(P),{skill:1,quiet:1}));sfx('rain')});break}
    case'mQ':p.atkAnim='cast';p.atkDur=p.atkT=.3;later(.1,()=>{shoot('p',p.x,p.y,a,16,'ice',1.3,{skill:1,freeze:2.6,pierce:3});sfx('ice')});break;
    case'mE':{p.atkAnim='cast';p.atkDur=p.atkT=.3;const [cx,cy]=ptAt(9);let tg=null,bd=3;for(const m of mobs)if(m.m===M.id&&!m.dying&&dist(m,p)<10){const dd=Math.hypot(m.x-cx,m.y-cy);if(dd<bd){bd=dd;tg=m}}if(!tg){zap(cx,cy);sfx('zap');break}const hitL=[tg];zap(tg.x,tg.y);hitMob(tg,1.8,{skill:1,shock:1});let cur=tg;for(let j=0;j<2;j++){let nx=null,nd=3.2;for(const m of mobs)if(m.m===M.id&&!m.dying&&!hitL.includes(m)){const dd=dist(m,cur);if(dd<nd){nd=dd;nx=m}}if(!nx)break;hitL.push(nx);const from=cur;later(.08*(j+1),()=>{fx.push({type:'arc',x:from.x,y:from.y,x2:nx.x,y2:nx.y,t:0,life:.22});if(!nx.dying)hitMob(nx,1,{skill:1,shock:1,quiet:1})});cur=nx}sfx('zap');break}
    case'mR':{const [tx,ty]=ptAt(8);p.atkAnim='cast';p.atkDur=p.atkT=.4;sfx('cast');teles.push({shape:'circle',x:tx,y:ty,r:2.6,t:0,dur:.55,team:'p',col:'#9ad8ff',fire:()=>{for(let i=0;i<6;i++)later(i*.2,()=>{let sx=tx+rnd(-1.8,1.8),sy=ty+rnd(-1.8,1.8);const near=mobs.filter(m=>m.m===M.id&&!m.dying&&Math.hypot(m.x-tx,m.y-ty)<2.8);if(near.length&&Math.random()<.6){const m=pick(near);sx=m.x;sy=m.y}zap(sx,sy);sfx('zap');shake=Math.max(shake,.15);pokePlants(sx,sy,1.2);for(const m of mobs)if(m.m===M.id&&!m.dying&&Math.hypot(m.x-sx,m.y-sy)<1.2+m.r)hitMob(m,1,{skill:1,shock:1})})}});break}
    case'lQ':{const t=nearestTo(ax,ay,6);if(!t){p.mp+=sk.mp;p.cds[k]=0;addText(p,'Sem alvo','#cfc6b8');return}const ba=Math.atan2(t.y-p.y,t.x-p.x);let nx=t.x+Math.cos(ba)*(t.r+.6),ny=t.y+Math.sin(ba)*(t.r+.6);if(blockedAt(M,nx,ny,.3)){nx=t.x-Math.cos(ba)*(t.r+.6);ny=t.y-Math.sin(ba)*(t.r+.6)}burstAt(p.x,p.y,0xa46aff,18,50);ghostFx(p,'#b06aff');p.x=nx;p.y=ny;unstick(M,p);burstAt(p.x,p.y,0xc08aff,18,50);elemBurst('void',p.x,p.y,12);p.d8=dir8(scrAng(t.x-p.x,t.y-p.y));p.nextCrit=1;p.ifr=.2;sfx('blink');break}
    case'lE':{p.dash={vx:Math.cos(a)*18,vy:Math.sin(a)*18,t:.25,dur:.25,hit:new Set(),bleed:1};p.ifr=.3;p.d8=dir8(scrAng(Math.cos(a),Math.sin(a)));sfx('dash');break}
    case'lR':{p.stealth=6;for(const m of mobs)if(m.target===p&&!m.def.boss){m.target=null;m.ret=true}burstAt(p.x,p.y,0x7a4ab0,24,40);elemBurst('void',p.x,p.y,14);addText(p,'Furtividade','#c08aff');sfx('blink');break}
    case'lT':{const t=nearestTo(ax,ay,5.5);if(!t){p.mp+=sk.mp;p.cds[k]=0;addText(p,'Sem alvo','#cfc6b8');return}const ba=Math.atan2(t.y-p.y,t.x-p.x),dd=Math.max(0,dist(p,t)-t.r-.5);p.dash={vx:Math.cos(ba)*dd/.2,vy:Math.sin(ba)*dd/.2,t:.2,dur:.2,leap:1};p.ifr=.3;p.atkAnim='atk';p.atkDur=p.atkT=.4;p.aimLock=ba;later(.22,()=>{if(t.dying)return;const ex=t.hp<t.maxHp*.3&&!t.def.boss?2:1;hitMob(t,4.5*ex,{skill:1,breakGuard:1,knock:2,melee:1});if(ex>1)addText(t,'EXECUÇÃO!','#ff4a3a',1);shake=Math.max(shake,.3);burstAt(t.x,t.y,0xc8202a,18,60);p.aimLock=null});break}
    case'hQ':p.atkAnim='cast';p.atkDur=p.atkT=.32;later(.1,()=>{shoot('p',p.x,p.y,a,18,'holy',1.7,{skill:1,holy:2,pierce:2});sfx('heal')});break;
    case'hE':{const h=Math.round(d.maxHp*(p.evo==='sac'?.42:.35));p.hp=Math.min(d.maxHp,p.hp+h);p.slowT=0;addText(p,'+'+h,'#7fe08a',1);burstAt(p.x,p.y,0xfff0a0,24,40);fx.push({type:'ring',x:p.x,y:p.y,r:1.4,t:0,life:.5,col:'#fff0a0'});sfx('heal');break}
    case'hR':p.buff.bless=12;addText(p,'Bênção','#fff0a0',1);fx.push({type:'ring',x:p.x,y:p.y,r:2,t:0,life:.6,col:'#fff0a0'});sfx('shout');break;
    case'hT':zones.push({x:p.x,y:p.y,r:2.4,t:6,tick:0,m:M.id});sfx('cast');break;
  }evoAfter(p,k,a,ax,ay)}
function pokePlants(x,y,r){for(const o of M.plants){if(Math.hypot(o.x-x,o.y-y)<r+.55){if(o.plant.t<=0){sfx('chime');burstAt(o.x,o.y,0x8affff,10,30);for(let i=0;i<6;i++)fx.push({type:'px',x:o.wx+rnd(-8,8),y:o.wy-rnd(6,20),vx:rnd(-6,6),vy:rnd(-20,-8),g:0,t:0,life:rnd(1,2),col:'#bff8ff',glow:1})}o.plant.t=8}}}
function nearestTo(x,y,r){let b=null,bd=r;for(const m of mobs){if(m.m!==M.id||m.dying||m.dead||m.def.ai==='dummy')continue;const d=Math.hypot(m.x-x,m.y-y);if(d<bd&&dist(m,P)<r+2){bd=d;b=m}}return b}
function recall(){burstAt(P.x,P.y,0xfff0b0,30,60);sfx('blink');if(M.id!=='world')changeMap('world',MAPS.world.temple[0],MAPS.world.temple[1]);else{P.x=MAPS.world.temple[0];P.y=MAPS.world.temple[1];unstick(M,P)}takeItem('scroll',1);uiDirty=1}
function usePotion(id){const p=P;if(!p||p.dead)return;const b=BASES[id];if(!countItem(id)){addText(p,'Sem '+b.n.toLowerCase(),'#cfc6b8');return}const d=D(p);
  if(b.buff){P.buff[b.buff]=b.dur;takeItem(id,1);sfx('drink');burstAt(p.x,p.y,b.ic[1],22,60);addText(p,b.n,'#ffd890',1);uiDirty=1;return}
  if(b.recall){if(p.combatT>0){addText(p,'Em combate','#ff8a7a');return}p.cast={t:3};addText(p,'Retornando...','#fff0b0');return}
  if(p.cds.pot>0){addText(p,`Poção em recarga (${Math.ceil(p.cds.pot)}s)`,'#cfc6b8');sfx('no');return}
  if(b.hp){if(p.hp>=d.maxHp)return;p.hp=Math.min(d.maxHp,p.hp+b.hp);addText(p,'+'+b.hp,'#7fe08a')}if(b.mp){if(p.mp>=d.maxMp)return;p.mp=Math.min(d.maxMp,p.mp+b.mp);addText(p,'+'+b.mp,'#8ab4ff')}p.cds.pot=CFG.potCD;takeItem(id,1);sfx('drink');uiDirty=1}
function shoot(team,x,y,a,spd,kind,mult,o,src){projs.push({team,x:x+Math.cos(a)*.3,y:y+Math.sin(a)*.3,vx:Math.cos(a)*spd,vy:Math.sin(a)*spd,a,kind,mult,o,src,life:kind==='garrow'?1:kind==='arcane'?2.2:.75,r:kind==='fire'?.35:.22,m:M.id,hit:new Set()})}
function explode(x,y,r,mult,o){pokePlants(x,y,r);fx.push({type:'ring',x,y,r,t:0,life:.35,col:'#ffb060'});for(let i=0;i<26;i++)burstAt(x,y,pick([0xffd060,0xff7a2a,0xc8401a,0x6a6a6a]),1,70);for(const m of mobs)if(m.m===M.id&&!m.dying&&Math.hypot(m.x-x,m.y-y)<r+m.r)hitMob(m,mult,o);shake=Math.max(shake,.15);sfx('boom')}
function updProjs(dt){for(let i=projs.length-1;i>=0;i--){const pr=projs[i];if(pr.m!==M.id){projs.splice(i,1);continue}pr.life-=dt;let dead=pr.life<=0;
    if(pr.kind==='arcane'&&!P.dead){const ta=Math.atan2(P.y-pr.y,P.x-pr.x);let da=ta-pr.a;while(da>Math.PI)da-=6.283;while(da<-Math.PI)da+=6.283;pr.a+=clamp(da,-1.6*dt,1.6*dt);const sp=Math.hypot(pr.vx,pr.vy);pr.vx=Math.cos(pr.a)*sp;pr.vy=Math.sin(pr.a)*sp}
    const steps=Math.max(1,Math.ceil(Math.hypot(pr.vx,pr.vy)*dt/.2));for(let s=0;s<steps&&!dead;s++){pr.x+=pr.vx*dt/steps;pr.y+=pr.vy*dt/steps;
      if(solidAt(M,pr.x,pr.y)&&!(M.terr[(pr.y|0)*M.w+(pr.x|0)]===WATER)){dead=true;if(pr.kind==='fire')explode(pr.x,pr.y,1.6,pr.mult,pr.o);else burstAt(pr.x,pr.y,0xc8b090,4,30);break}
      if(pr.team==='p'&&M.plants.length)pokePlants(pr.x,pr.y,.15);
      if(pr.team==='p'||pr.team==='b'){for(const m of mobs){if(m.m!==M.id||m.dying||pr.hit.has(m.id))continue;if(Math.hypot(m.x-pr.x,m.y-pr.y)<m.r+pr.r){pr.hit.add(m.id);if(pr.team==='b'){botHit(m,pr.src,pr.mult)}else if(pr.kind==='fire')explode(pr.x,pr.y,1.6,pr.mult,pr.o);else{hitMob(m,pr.mult,pr.o);if(pr.o&&pr.o.onHit)pr.o.onHit(m,pr);if(pr.o&&pr.o.el)elemBurst(pr.o.el,m.x,m.y,9);else if(pr.kind==='arrow'||pr.kind==='quarrel')burstAt(m.x,m.y,0xf0e8d8,5,60)}if(pr.o&&pr.o.pierce>0){pr.o=Object.assign({},pr.o,{pierce:pr.o.pierce-1})}else dead=true;break}}}
      else if(pr.team==='m'&&!P.dead&&Math.hypot(P.x-pr.x,P.y-pr.y)<P.r+pr.r){hurtPlayer(pr.mult,pr.src,{});dead=true}}
    if(pr.kind==='fire'&&Math.random()<.8)fx.push({type:'p',x:pr.x,y:pr.y,vx:rnd(-.5,.5),vy:rnd(-.5,.5),t:0,life:.35,col:pick(['#ffd060','#ff7a2a','#c8401a']),tile:1,up:12});
    if((pr.team==='p'||pr.team==='v')&&pr.o&&pr.o.el&&['arrow','quarrel','dagger','note','bigarrow','dragon'].includes(pr.kind)&&Math.random()<(pr.kind==='dragon'?1:.85))fx.push({type:'p',x:pr.x,y:pr.y,vx:rnd(-.4,.4),vy:pr.o.el==='fire'?rnd(-1,-.3):rnd(-.4,.4),t:0,life:.35,col:pick(ELC[pr.o.el]),tile:1,up:12});
    if(pr.kind==='ice'&&Math.random()<.8)fx.push({type:'p',x:pr.x,y:pr.y,vx:rnd(-.4,.4),vy:rnd(-.4,.4),t:0,life:.35,col:pick(['#ffffff','#bfe8ff','#7ac8f0']),tile:1,up:12});
    if(pr.kind==='holy'&&Math.random()<.7)fx.push({type:'p',x:pr.x,y:pr.y,vx:0,vy:0,t:0,life:.3,col:'#fff0a0',tile:1,up:12});
    if(pr.kind==='bolt'||pr.kind==='arcane')if(Math.random()<.6)fx.push({type:'p',x:pr.x,y:pr.y,vx:0,vy:0,t:0,life:.3,col:pr.kind==='arcane'?'#8affff':'#b8d0ff',tile:1,up:10});
    if(dead)projs.splice(i,1)}}
// ---------- mobs ----------
function lvMult(diff){return clamp(1+diff*.12,.2,1.6)}
function spawnMob(kind,m,rect,at){const def=MOBS[kind];let x,y;if(at){x=at[0];y=at[1]}else{for(let i=0;i<80;i++){x=rint(rect[0],rect[2])+.5;y=rint(rect[1],rect[3])+.5;if(walkable(m,Math.floor(x),Math.floor(y),true)&&tAt(m,x,y)!==DIRT)break}}
  const lv=def.boss||def.elite||def.ai==='dummy'?def.lv:def.lv+rint(-1,1),k=(1+(lv-def.lv)*.12)*(def.ai==='dummy'?1:CFG.mobHp);
  const mb={id:uid++,type:'mob',kind,def,m:m.id,x,y,hx:x,hy:y,lv,hp:Math.round(def.hp*k),maxHp:Math.round(def.hp*k),atk:def.atk*k/CFG.mobHp*CFG.mobAtk,r:def.r||.35,look:MLOOK[def.look],d8:rint(0,7),face:Math.random()*6.28,anim:'idle',frame:0,animT:Math.random()*3,atkCD:rnd(.5,1.5),cd2:rnd(1,3),cd3:2,cdSlam:4,cdCharge:6,flash:0,hpShow:0,stunT:0,slowT:0,rootT:0,kx:0,ky:0,target:null,wT:rnd(0,3),path:[],rp:0,rect,dying:0,dps:[],atkT:0,z:0};
  if(def.boss&&m.bossDown){m.bossDown=false;for(const a of m.acts)if(a.kind==='bchest'){a.opened=false;if(a.obj)a.obj.cv=ART.chest.cv}}
  if(!def.boss&&!def.elite&&def.ai!=='dummy'&&def.ai!=='scarecrow'&&!at&&Math.random()<.06){mb.champ=1;mb.maxHp=Math.round(mb.maxHp*2.6);mb.hp=mb.maxHp;mb.atk*=1.35;mb.look=Object.assign({},mb.look,{scale:(mb.look.scale||1)*1.18})}
  if(def.ai==='scarecrow'){mb.sleep=1;mb.z=7;mb.d8=dir8(scrAng(1,1))}mobs.push(mb);return mb}
function wakeScare(m){m.sleep=0;m.d8=dir8(scrAng(P.x-m.x,P.y-m.y));m.look=MLOOK.scarecrow_w;m.wakeT=.65;m.target=P;m.ret=false;say(m,pick(['Sai da minha plantação...','*range* *range*','Hhhh... colheita...','Ninguém toca no trigo.']),2.2);for(let i=0;i<3;i++)burstAt(m.x,m.y,pick([0xd8b860,0xb89848,0x8a6a3a]),8,70);shake=Math.max(shake,.15);sfx('scare')}
function aggro(m,t){if(m.def.ai==='dummy')return;if(m.sleep){wakeScare(m);return}if(!m.target){m.target=t;m.ret=false;if(m.def.fam==='goblin'||m.def.fam==='morto-vivo'){if(!m.shouted&&Math.random()<.5&&m.def.fam==='goblin'){m.shouted=1;say(m,pick(['Intruso!','Pega ele!','Humano!']))}for(const o of mobs)if(o!==m&&o.m===m.m&&!o.target&&o.def.fam===m.def.fam&&dist(o,m)<7&&!o.dying)o.target=t}
  if(m.def.boss){bossActive=m;say(m,{goblin_chefe:'Quem ousa entrar na minha toca?!',goblin_rei:'Ajoelhe-se diante do REI!',abade:'Mais um para o meu ossuário...'}[m.kind]||'...');sfx('roar')}}}
function say(e,txt,t=3){e.bub={txt,t}}
function hitMob(m,mult,o={}){if(m.dead||m.dying)return 0;if(!o.pet&&lvMiss(m,o)){if(!m.target)aggro(m,P);m.hpShow=6;return 0}const d=D();let dmg=d.atk*mult*rnd(.9,1.1);if(!o.pet)dmg*=comboMult(o)*evoDmg(m,o)*lvPen(m,o);const fam=m.def.fam;if(fam==='fera')dmg*=1+d.A.vsBeast/100;if(fam==='goblin')dmg*=1+d.A.vsGoblin/100;if(fam==='morto-vivo')dmg*=1+d.A.vsUndead/100;if(o.skill)dmg*=1+d.A.skill/100;if(o.holy&&fam==='morto-vivo')dmg*=o.holy>1?2:1.5;const shatter=o.shock&&m.frozenT>0;if(shatter)dmg*=2;
  let crit=Math.random()*100<d.crit+comboCrit();if(P.nextCrit&&!o.quiet){crit=true;P.nextCrit=0}if(crit)dmg*=critMult();let tag=null;if(P.cls==='l'&&!o.quiet){if(P.stealth>0){dmg*=3;P.stealth=0;tag='ASSASSINATO!'}else if(o.melee&&(m.target!==P||m.stunT>0)){dmg*=1.6;tag='Pelas costas!'}}dmg*=1-m.def.def/(m.def.def+50);let blocked=false;
  if(m.def.block&&!o.breakGuard&&m.stunT<=0){const ta=Math.atan2(P.y-m.y,P.x-m.x);if(angDiff(ta,m.face)<1.15){dmg*=.25;blocked=true}}
  dmg=Math.max(1,Math.round(dmg));
  if(m.def.ai==='dummy'){m.dps.push([T,dmg]);if(!m.dpsShow)m.dpsShow=0}else m.hp-=dmg;
  m.flash=.1;m.hpShow=6;if(!m.target)aggro(m,P);P.combatT=5;
  const ka=Math.atan2(m.y-P.y,m.x-P.x),kn=(o.knock||.8)*(m.def.boss?.15:1);if(shatter){m.frozenT=0;addText(m,'Estilhaçou!','#bfe8ff',1);for(let i=0;i<22;i++)burstAt(m.x,m.y,pick([0xffffff,0xbfe8ff,0x7ac8f0]),1,70);sfx('shatter');hitstop=Math.max(hitstop,.06)}if(o.freeze&&!shatter){if(m.def.boss)m.slowT=Math.max(m.slowT,3);else{if(!(m.frozenT>0))sfx('freeze');m.frozenT=o.freeze;m.atkT=0}}if(m.def.ai!=='dummy'&&!(m.frozenT>0)){m.kx=Math.cos(ka)*kn*2.2;m.ky=Math.sin(ka)*kn*2.2}
  if(o.burn&&m.def.ai!=='dummy'){m.bleedT=3;m.bleedTick=.5;m.burn=1;m.poison=0}if(o.poison&&m.def.ai!=='dummy'){m.bleedT=5;m.bleedTick=.5;m.poison=1;m.burn=0}if(o.bleed&&m.def.ai!=='dummy'&&Math.random()<o.bleed){m.bleedT=4;m.bleedTick=.5;m.burn=0;m.poison=0;addText(m,'Sangrando','#ff6a84')}if(P.stealth>0&&!o.quiet)P.stealth=0;if(o.stun&&!m.def.boss)m.stunT=Math.max(m.stunT,o.stun);if(o.slow){m.slowT=o.slow}if(o.root)m.rootT=o.root;
  if(blocked){addText(m,'Bloqueou','#c8d0e0');burstAt(m.x,m.y,0xe8e8f0,8,50);sfx('block')}else{addText(m,dmg,crit?'#ffd23a':'#ffffff',crit);if(tag)addText(m,tag,'#ff6a5a',1);burstAt(m.x,m.y,crit?0xffd23a:0xf0e8e0,o.quiet?2:crit?12:6,45);if(!o.quiet)sfx(crit?'crit':hitSnd(o));hitFx(m,crit,o)}
  if(crit){hitstop=Math.max(hitstop,.045);shake=Math.max(shake,.12)}
  if(d.A.life)P.hp=Math.min(d.maxHp,P.hp+dmg*d.A.life/100);
  if(!o.pet&&!blocked)onPlayerHit(m,o,dmg);
  if(m.hp<=0)killMob(m,P);return dmg}
function botHit(m,b,mult){if(m.dying||!b)return;const dmg=Math.max(1,Math.round((8+b.lv*3)*mult*rnd(.85,1.15)));if(m.def.ai!=='dummy')m.hp-=dmg;m.flash=.1;m.hpShow=4;addText(m,dmg,'#b8b0a4');if(!m.botAgg)m.botAgg=b;if(m.hp<=0)killMob(m,b)}
function hurtPlayer(mult,src,o={}){const p=P;if(p.dead)return;const d=D();if(p.ifr>0){addText(p,'Esquivou!','#9ad0ff');return}if(Math.random()*100<d.dodge){addText(p,'Esquiva','#9ad0ff');return}
  let dmg=(src&&src.atk?src.atk:10)*mult*rnd(.9,1.1)*(1-d.def/(d.def+80));if(src&&src.def&&src.def.fam==='morto-vivo')dmg*=1-d.A.vsUndead/100;dmg=Math.max(1,Math.round(dmg));dmg=evoTaken(dmg,src);if(dmg>0)dmg=Math.round(treeTaken(dmg));if(dmg<=0)return;
  p.hp-=dmg;p.flash=.12;p.combatT=5;p.cast=null;addText(p,dmg,'#ff5a4a');sfx('hurt');shake=Math.max(shake,.1);
  if(o.knock&&src){const a=o.ang??Math.atan2(p.y-src.y,p.x-src.x);p.kx=Math.cos(a)*o.knock*2;p.ky=Math.sin(a)*o.knock*2}
  if(p.hp<=0){p.hp=0;if(!angelSave())die()}}
function die(){const p=P;closeCircle();p.dead=true;p.deadT=0;p.dash=null;const loss=Math.round(need(p.lv)*CFG.deathXpLoss);p.exp=Math.max(0,p.exp-loss);const gl=Math.floor(p.gold*CFG.deathGoldLoss);for(const l of loots)if(l.tomb)l.t=0;if(gl>0){p.gold-=gl;loots.push({tomb:1,gold:gl,x:p.x,y:p.y,m:M.id,t:900,age:1})}log(`Você caiu e perdeu ${loss} XP.${gl?` ${gl} de ouro ficaram na sua lápide, onde você caiu. Volte para buscar.`:''}`,'bad');for(const m of mobs)if(m.target===p)m.target=null;if(bossActive){resetBoss()}later(1.4,()=>showWin('#death'));sfx('die')}
function resetBoss(){const b=bossActive;if(b&&!b.dying){b.hp=b.maxHp;b.target=null;b.x=b.hx;b.y=b.hy;b.s1=b.s2=0}bossActive=null}
function revive(){const p=P;const d=D();p.dead=false;p.dash=null;p.cast=null;p.stun=0;p.slowT=0;p.atkT=0;p.kx=p.ky=0;input.mdown=false;input.keys={};p.hp=Math.round(d.maxHp*.6);p.mp=Math.round(d.maxMp*.6);hideWin('#death');{const hm=homeMap();changeMap(hm,MAPS[hm].temple[0],MAPS[hm].temple[1])}burstAt(p.x,p.y,0xfff0b0,24,50);save()}
function gainExp(x,why){const p=P;p.exp+=x;if(why)addText(p,`+${x} XP`,'#c8b0ff');while(p.exp>=need(p.lv)){p.exp-=need(p.lv);p.lv++;p.pts+=CFG.ptsPerLevel;const d=D();p.hp=d.maxHp;p.mp=d.maxMp;lvlFx=1.8;sfx('lvl');burstAt(p.x,p.y,0xffd23a,30,70);log(`Nível ${p.lv}! Você ganhou ${CFG.ptsPerLevel} pontos de atributo (C).`,'sys');
    for(const k of skKeys(p)){const sk=skillSet(p)[k];if(sk.lv===p.lv)log(`Nova habilidade: ${sk.n} [${k}]`,'sys')}if(Math.random()<.6)later(1.2,()=>{const b=pick(bots);if(b)botSay(b,pick(['gz '+p.name,'parabéns pelo up!','up! boa','rumo ao 60 kkk']))})}uiDirty=1}
function killMob(m,by){if(m.dying)return;m.dying=.7;m.target=null;m.anim='idle';const d=m.def;burstAt(m.x,m.y,0x8a7a6a,12,50);if(d.ai==='dummy'){m.dying=0;return}
  if(d.rs>0)respawnQ.push({t:d.rs*rnd(.9,1.2),kind:m.kind,m:m.m,rect:m.rect,at:d.boss?[m.hx,m.hy]:null});
  if(d.boss&&MAPS[m.m]){MAPS[m.m].bossDown=true}
  if(d.boss){bossActive=null;sfx('victory');log(`${d.n} caiu! O lugar fica em silêncio por um tempo.`,'sys');toast('Vitória!',`${d.n} foi derrotado`)}
  if(by!==P&&!(by&&by.type==='pet'))return;onKillStats(m);rqOnKill(m.kind);const xp=Math.max(1,Math.round(d.exp*lvMult(m.lv-P.lv)*(1+(m.lv-d.lv)*.12)*(1+.15*partyNear())*(m.champ?3:1)*evXp()));gainExp(xp,1);
  const g=rint(d.gold[0],d.gold[1]);if(g>0)loots.push({gold:g,x:m.x+rnd(-.3,.3),y:m.y+rnd(-.3,.3),m:m.m,t:90,age:0});
  const luck=P.buff&&P.buff.luck>0?1.4:1;for(const [id,ch] of d.drops)if(Math.random()<ch*luck){const it=makeItem(id,0);loots.push({item:it,x:m.x+rnd(-.5,.5),y:m.y+rnd(-.5,.5),m:m.m,t:120,age:0})}
  if(d.elite||m.champ){const n=Math.random()<.4?2:1;for(let i=0;i<n;i++){const pool=DROP_POOL.filter(id=>BASES[id].lv<=m.lv+3),mine=pool.filter(id=>!BASES[id].cls||BASES[id].cls===P.cls);const id=pick(Math.random()<.7&&mine.length?mine:pool);loots.push({item:makeItem(id,Math.max(1,rollRar(d.elite?2.2:1.6))),x:m.x+rnd(-.6,.6),y:m.y+rnd(-.6,.6),m:m.m,t:150,age:0})}
    if(Math.random()<(d.elite?.35:.15)){const rare=Object.keys(BASES).filter(id=>BASES[id].dropOnly&&BASES[id].lv<=m.lv+4&&(!BASES[id].cls||BASES[id].cls===P.cls));if(rare.length){const id=pick(rare);loots.push({item:makeItem(id,BASES[id].u?0:2),x:m.x,y:m.y-.4,m:m.m,t:180,age:0});log(`${d.elite?'O elite':'O campeão'} deixou cair algo raro: ${BASES[id].n}!`,'loot','#ffa53a')}}}
  else if(Math.random()<d.eq*CFG.eqDrop){const boost=d.boss?1.5:0;const pool=DROP_POOL.filter(id=>BASES[id].lv<=m.lv+2);const mine=pool.filter(id=>!BASES[id].cls||BASES[id].cls===P.cls);const id=pick(Math.random()<.7&&mine.length?mine:pool);loots.push({item:makeItem(id,rollRar(boost)),x:m.x+rnd(-.5,.5),y:m.y+rnd(-.5,.5),m:m.m,t:120,age:0})}
  if(m.kind==='guardiao'){P.q.tumulo=3;log('O Guardião Esquecido se desfaz em névoa azul. "Obrigado... por lembrar."','npc');gainExp(150,1)}
  if(m.kind==='anciao'){P.q.santuario=3;log('O Ancião Lunar se desfaz em vagalumes. O santuário fica em paz.','npc')}
  if(m.kind==='lobo_alfa')log('O Lobo Alfa tomba. A pele dele vale uma história.','sys');uiDirty=1}
function mobMoveTo(m,tx,ty,mult,dt){if(m.rootT>0)return;steer(m,tx,ty,m.def.spd*CFG.mobSpd*mult*(m.slowT>0?.5:1)*(m.buffT>0?1.3:1),dt,true)}
function updMob(m,dt){if(m.dying){m.dying-=dt;if(m.dying<=0){m.dying=0;m.dead=true}return}
  const d=m.def;m.atkCD-=dt;m.cd2-=dt;m.cd3-=dt;m.cdSlam-=dt;m.cdCharge-=dt;m.flash-=dt;if(m.flinch>0)m.flinch-=dt;m.hpShow-=dt;m.stunT-=dt;m.frozenT=(m.frozenT||0)-dt;m.slowT-=dt;m.rootT-=dt;m.atkT-=dt;m.buffT=(m.buffT||0)-dt;if(m.bub&&(m.bub.t-=dt)<=0)m.bub=null;m.moving=false;
  if(m.kx||m.ky){tryMove(M,m,m.kx*dt,m.ky*dt);const f=Math.pow(.003,dt);m.kx*=f;m.ky*=f;if(Math.abs(m.kx)+Math.abs(m.ky)<.05)m.kx=m.ky=0}
  for(const o of mobs)if(o!==m&&o.m===m.m&&!o.dying){const dd=dist(o,m),mn=(o.r+m.r)*.9;if(dd<mn&&dd>.001){const pu=(mn-dd)*.5;tryMove(M,m,(m.x-o.x)/dd*pu,(m.y-o.y)/dd*pu)}}
  if(m.bleedT<=0){m.burn=0;m.poison=0}if(m.bleedT>0){m.bleedT-=dt;m.bleedTick-=dt;if(m.bleedTick<=0){m.bleedTick=.5;hitMob(m,.22,{quiet:1});burstAt(m.x,m.y,m.burn?0xff8a2a:m.poison?0x7ad83a:0xa81a22,3,20)}}
  if(d.ai==='dummy'){m.d8=1;m.dps=m.dps.filter(e=>T-e[0]<5);return}
  if(m.leap){const L=m.leap;L.t+=dt;const k=Math.min(1,L.t/L.dur);m.x=lerp(L.fx,L.tx,k);m.y=lerp(L.fy,L.ty,k);m.z=Math.sin(k*Math.PI)*18;if(k>=1){m.leap=null;m.z=0;burstAt(m.x,m.y,0x8a7a5a,14,50);if(!P.dead&&Math.hypot(P.x-m.x,P.y-m.y)<1.4)hurtPlayer(1.8,m,{knock:4})}return}
  if(m.frozenT>0){m.kx=m.ky=0;return}
  if(m.stunT>0){m.anim=d.look==='boar'?'stun':'idle';m.frame=0;return}
  if(m.charge){const c=m.charge;c.t-=dt;const ox=m.x,oy=m.y;tryMove(M,m,Math.cos(c.a)*c.spd*dt,Math.sin(c.a)*c.spd*dt);m.anim='walk';m.animT+=dt*3;m.frame=Math.floor(m.animT*10)%8;if(Math.random()<.7)burstAt(m.x,m.y,0x9a8a6a,1,20);
    if(!c.hit&&!P.dead&&dist(m,P)<.8+m.r){c.hit=1;hurtPlayer(c.mult,m,{knock:c.knock,ang:c.a});c.t=0}
    if(Math.hypot(m.x-ox,m.y-oy)<c.spd*dt*.3){c.t=0;if(d.ai==='boar'){m.stunT=1.8;say(m,'Atordoado!',1.6);shake=Math.max(shake,.25);sfx('thud');burstAt(m.x,m.y,0xc8c0b0,12,50)}}
    if(c.t<=0)m.charge=null;return}
  if(m.wind){m.wind.t-=dt;m.anim=m.wind.anim||'atk';m.frame=clamp(Math.floor((1-m.wind.t/m.wind.dur)*3),0,2);if(m.wind.t<=0){const w=m.wind;m.wind=null;m.anim='atk';m.frame=3;m.atkT=.15;w.fire()}return}
  if(d.ai==='scarecrow'){if(m.sleep){m.anim='idle';m.frame=0;m.z=7;m.d8=dir8(scrAng(1,1));if(!P.dead&&P.map===m.m&&!(P.stealth>0)&&dist(m,P)<2.6)wakeScare(m);return}if(m.wakeT>0){m.wakeT-=dt;m.z=Math.max(0,m.z-dt*30);m.anim='idle';return}}
  if(m.atkT>0){m.anim='atk';m.frame=3;return}
  if(d.ai==='ghost'&&m.kind==='guardiao'&&!m.target&&!isNight()){m.dying=.8;return}
  if(!m.target&&d.aggro&&!P.dead&&P.map===m.m&&!safeAt(M,P.x,P.y)&&!(P.stealth>0&&dist(m,P)>1)&&dist(m,P)<d.aggro*(isNight()&&d.fam==='fera'?1.4:1))aggro(m,P);
  let t=m.target;
  if(t){const home=Math.hypot(m.x-m.hx,m.y-m.hy);if(t.dead||P.map!==m.m||safeAt(M,t.x,t.y)||home>(d.boss?13:17)||(P.stealth>0&&!d.boss&&dist(m,P)>1.2)){m.target=null;m.ret=true;if(d.boss)resetBoss();t=null}}
  if(!t){if(m.botAgg&&!m.botAgg.dead&&dist(m,m.botAgg)<7&&!d.boss){const b=m.botAgg;if(dist(m,b)>1.2)mobMoveTo(m,b.x,b.y,.9,dt);else if(m.atkCD<=0){m.atkCD=1.4;m.atkT=.25;m.d8=dir8(scrAng(b.x-m.x,b.y-m.y))}}
    else{m.botAgg=null;if(m.ret){mobMoveTo(m,m.hx,m.hy,1,dt);if(Math.hypot(m.x-m.hx,m.y-m.hy)<.6){m.ret=false;m.hp=m.maxHp;if(d.ai==='scarecrow'){m.sleep=1;m.x=m.hx;m.y=m.hy;m.look=MLOOK.scarecrow}}}else{m.wT-=dt;if(m.wT<=0){m.wT=rnd(2.5,6);if(!d.boss&&Math.random()<.65){m.wx=m.hx+rnd(-4,4);m.wy=m.hy+rnd(-4,4);if(!walkable(M,Math.floor(m.wx),Math.floor(m.wy),true))m.wx=null}else m.wx=null}if(m.wx!=null){mobMoveTo(m,m.wx,m.wy,.4,dt);if(Math.hypot(m.x-m.wx,m.y-m.wy)<.3)m.wx=null}}}}
  else{const dd=dist(m,t),a=Math.atan2(t.y-m.y,t.x-m.x);const W=(dur,fire,anim)=>{m.wind={t:dur,dur,fire,anim};m.face=a;m.d8=dir8(scrAng(Math.cos(a),Math.sin(a)))};
    switch(d.ai){
      case'boar':if(dd<1.4&&m.atkCD<=0){m.atkCD=1.5;W(.38,()=>{if(dist(m,P)<1.7+P.r)hurtPlayer(1,m,{knock:2})})}else if(m.cd2<=0&&dd>2.2&&dd<7&&los(M,m,t)){m.cd2=rnd(4,5.5);teles.push({shape:'line',x:m.x,y:m.y,a,len:6.8,w:1,t:0,dur:.8,team:'m'});say(m,'*bufa*',.8);W(.8,()=>{m.charge={a,t:.62,spd:10.5,mult:1.6,knock:6}},'idle')}else mobMoveTo(m,t.x,t.y,1,dt);break;
      case'wolf':if(!m.howled){m.howled=1;say(m,'Auuuu!',1.4);sfx('howl');for(const o of mobs)if(o!==m&&o.m===m.m&&!o.target&&o.def.ai==='wolf'&&dist(o,m)<9)o.target=t;if(d.alpha)for(const o of mobs)if(o.def.ai==='wolf'&&dist(o,m)<10)o.buffT=10}
        if(m.strafe>0){m.strafe-=dt;const sa=a+m.sdir*Math.PI/2;steer(m,m.x+Math.cos(sa),m.y+Math.sin(sa),d.spd*.8,dt,true);m.d8=dir8(scrAng(Math.cos(a),Math.sin(a)))}
        else if(dd<1.3&&m.atkCD<=0){m.atkCD=1.3;W(.3,()=>{if(dist(m,P)<1.6+P.r)hurtPlayer(1,m,{knock:1});m.strafe=.55;m.sdir=Math.random()<.5?-1:1})}
        else if(d.alpha&&m.cd2<=0&&dd>2&&dd<5.5){m.cd2=6;const tx=t.x,ty=t.y;teles.push({shape:'circle',x:tx,y:ty,r:1.4,t:0,dur:.7,team:'m'});W(.7,()=>{m.leap={fx:m.x,fy:m.y,tx,ty,t:0,dur:.35}})}
        else mobMoveTo(m,t.x,t.y,1,dt);break;
      case'scarecrow':if(dd<1.5&&m.atkCD<=0){m.atkCD=1.6;const fa=a;teles.push({shape:'cone',x:m.x,y:m.y,a:fa,r:1.9,arc:1.6,t:0,dur:.55,team:'m'});W(.55,()=>{fx.push({type:'slash',x:m.x,y:m.y,a:fa,r:1.8,t:0,life:.2,arc:2,col:'#d8b860',dim:1});for(const q of [P])if(dist(m,P)<1.9+P.r&&angDiff(Math.atan2(P.y-m.y,P.x-m.x),fa)<.85)hurtPlayer(1.15,m,{knock:2})})}else mobMoveTo(m,t.x,t.y,1,dt);break;
      case'goblin':if(m.hp<m.maxHp*.25&&!m.fled&&!d.noFlee){m.fled=1;m.flee=2.5;say(m,'Socorro!')}
        if(m.flee>0){m.flee-=dt;mobMoveTo(m,m.x-Math.cos(a)*2,m.y-Math.sin(a)*2,1.1,dt)}else if(dd<1.35&&m.atkCD<=0){m.atkCD=1.25;W(.4,()=>{if(dist(m,P)<1.7+P.r)hurtPlayer(1,m,{knock:1.5})})}else mobMoveTo(m,t.x,t.y,1,dt);break;
      case'archer':{const sight=los(M,m,t);if(dd<3.4)mobMoveTo(m,m.x-Math.cos(a)*2,m.y-Math.sin(a)*2,.9,dt);else if(dd>7.5||!sight)mobMoveTo(m,t.x,t.y,1,dt);else if(m.atkCD<=0){m.atkCD=rnd(1.8,2.3);teles.push({shape:'line',x:m.x,y:m.y,a,len:8,w:.28,t:0,dur:.55,team:'m',thin:1});W(.55,()=>{shoot('m',m.x,m.y,a,11,'garrow',1,{},m);sfx('bow')},'bow')}else m.d8=dir8(scrAng(Math.cos(a),Math.sin(a)));break}
      case'guard':{let da=a-m.face;while(da>Math.PI)da-=6.283;while(da<-Math.PI)da+=6.283;m.face+=clamp(da,-2.2*dt,2.2*dt);m.d8=dir8(scrAng(Math.cos(m.face),Math.sin(m.face)));
        if(dd<1.7&&m.atkCD<=0){m.atkCD=2.4;const cx=m.x+Math.cos(m.face)*1.1,cy=m.y+Math.sin(m.face)*1.1;teles.push({shape:'circle',x:cx,y:cy,r:1.25,t:0,dur:.85,team:'m'});m.wind={t:.85,dur:.85,fire:()=>{shake=Math.max(shake,.2);burstAt(cx,cy,0x9a8a6a,10,40);sfx('thud');if(Math.hypot(P.x-cx,P.y-cy)<1.25+P.r)hurtPlayer(1.8,m,{knock:4})}}}
        else{const f=m.face;mobMoveTo(m,t.x,t.y,.8,dt);m.face=f;m.d8=dir8(scrAng(Math.cos(f),Math.sin(f)))}break}
      case'boss':{const enr=m.hp/m.maxHp<.3?.72:1;
        if(!m.s1&&m.hp<m.maxHp*.66){m.s1=1;say(m,'A mim, guerreiros!');sfx('roar');const minion=d.minions||(m.kind==='goblin_rei'?['goblin_guer','goblin_xama']:['goblin','goblin']);for(let i=0;i<2;i++){const g=spawnMob(minion[i],M,null,[m.x+rnd(-2,2),m.y+rnd(-2,2)]);g.def=Object.assign({},g.def,{rs:0});g.target=P}}
        if(!m.s2&&m.hp<m.maxHp*.33){m.s2=1;say(m,'Vocês vão PAGAR!');sfx('roar');for(const k of (d.minions?[d.minions[0],d.minions[1],d.minions[0]]:m.kind==='goblin_rei'?['goblin_arq','goblin_guer','goblin_arq','goblin']:['goblin_arq','goblin_arq','goblin'])){const g=spawnMob(k,M,null,[m.x+rnd(-3,3),m.y+rnd(-3,3)]);g.def=Object.assign({},g.def,{rs:0});g.target=P}}
        if(m.cdSlam<=0&&dd<3){m.cdSlam=7;teles.push({shape:'circle',x:m.x,y:m.y,r:3.2,t:0,dur:1.1*enr,team:'m'});W(1.1*enr,()=>{shake=.5;sfx('boom');fx.push({type:'ring',x:m.x,y:m.y,r:3.3,t:0,life:.4,col:'#c8b090'});for(let i=0;i<30;i++){const aa=Math.random()*6.28,rr=Math.random()*3;burstAt(m.x+Math.cos(aa)*rr,m.y+Math.sin(aa)*rr,0x9a8a6a,1,40)}if(dist(m,P)<3.2+P.r)hurtPlayer(2,m,{knock:6})})}
        else if(m.cdCharge<=0&&dd>3.5&&los(M,m,t)){m.cdCharge=9;teles.push({shape:'line',x:m.x,y:m.y,a,len:8.5,w:1.5,t:0,dur:.85*enr,team:'m'});say(m,'RAAAH!',1);W(.85*enr,()=>{m.charge={a,t:.7,spd:12,mult:1.6,knock:8}},'idle')}
        else if(dd<2.7&&m.atkCD<=0){m.atkCD=2.1*enr;teles.push({shape:'cone',x:m.x,y:m.y,a,r:2.8,arc:1.8,t:0,dur:.72*enr,team:'m'});W(.72*enr,()=>{sfx('swing');fx.push({type:'slash',x:m.x,y:m.y,a,r:2.6,t:0,life:.22,arc:1.8,heavy:1});if(dist(m,P)<2.8+P.r&&angDiff(Math.atan2(P.y-m.y,P.x-m.x),a)<.95)hurtPlayer(1.3,m,{knock:3})})}
        else mobMoveTo(m,t.x,t.y,enr<1?1.25:1,dt);break}
      case'shaman':{let hurt=null;for(const o of mobs)if(o!==m&&o.m===m.m&&!o.dying&&o.def.fam==='goblin'&&o.hp<o.maxHp*.8&&dist(o,m)<7&&(!hurt||o.hp/o.maxHp<hurt.hp/hurt.maxHp))hurt=o;
        if(hurt&&m.cd2<=0){m.cd2=4;const tgt=hurt;W(.6,()=>{if(tgt.dying)return;const h=Math.round(tgt.maxHp*.18);tgt.hp=Math.min(tgt.maxHp,tgt.hp+h);addText(tgt,'+'+h,'#7fe08a');fx.push({type:'beam',x:m.x,y:m.y,x2:tgt.x,y2:tgt.y,t:0,life:.4,col:'#8affa0'});burstAt(tgt.x,tgt.y,0x8affa0,10,30);sfx('heal')},'cast');say(m,pick(['Ugh-ma!','Cura!']),1)}
        else if(dd<4)mobMoveTo(m,m.x-Math.cos(a)*2,m.y-Math.sin(a)*2,.9,dt);else if(dd>8||!los(M,m,t))mobMoveTo(m,t.x,t.y,1,dt);else if(m.atkCD<=0){m.atkCD=2.4;W(.5,()=>{shoot('m',m.x,m.y,Math.atan2(P.y-m.y,P.x-m.x),7,'arcane',.8,{},m);sfx('bolt')},'cast')}else m.d8=dir8(scrAng(Math.cos(a),Math.sin(a)));break}
      case'lich':{const enr=m.hp/m.maxHp<.35?.75:1;
        if(!m.s1&&m.hp<m.maxHp*.66){m.s1=1;say(m,'Levantem-se!');sfx('roar');for(const k of (d.minions?[d.minions[0],d.minions[0],d.minions[1]]:['esqueleto','esqueleto','esq_arq'])){const g=spawnMob(k,M,null,[m.x+rnd(-3,3),m.y+rnd(-2,3)]);g.def=Object.assign({},g.def,{rs:0});g.target=P;burstAt(g.x,g.y,0xb07aff,14,40)}}
        if(!m.s2&&m.hp<m.maxHp*.33){m.s2=1;say(m,'O ossuário não acaba!');sfx('roar');for(const k of (d.minions?[d.minions[1],d.minions[0],d.minions[1],d.minions[0]]:['espectro','esqueleto','esq_arq','esqueleto'])){const g=spawnMob(k,M,null,[m.x+rnd(-3,3),m.y+rnd(-2,3)]);g.def=Object.assign({},g.def,{rs:0});g.target=P}}
        if(dd<2.2&&m.cd2<=0){m.cd2=7;burstAt(m.x,m.y,0xb07aff,20,50);const ba=Math.atan2(m.y-P.y,m.x-P.x);for(let s=5;s>1;s-=.5){const nx=m.hx+Math.cos(ba+rnd(-1,1))*s,ny=m.hy+Math.sin(ba+rnd(-1,1))*s;if(!blockedAt(M,nx,ny,.5)){m.x=nx;m.y=ny;break}}burstAt(m.x,m.y,0xb07aff,20,50);sfx('blink')}
        else if(m.cdSlam<=0&&dd<4){m.cdSlam=8;teles.push({shape:'circle',x:m.x,y:m.y,r:3.4,t:0,dur:1.2*enr,team:'m'});W(1.2*enr,()=>{fx.push({type:'ring',x:m.x,y:m.y,r:3.5,t:0,life:.45,col:'#c89aff'});sfx('boom');shake=.35;if(dist(m,P)<3.4+P.r)hurtPlayer(1.9,m,{knock:5})},'cast')}
        else if(m.atkCD<=0&&dd<10){m.atkCD=2.2*enr;W(.55*enr,()=>{for(const o of [-.35,0,.35])shoot('m',m.x,m.y,Math.atan2(P.y-m.y,P.x-m.x)+o,6.5,'arcane',.9,{},m);sfx('bolt')},'cast')}
        else if(dd>6)mobMoveTo(m,t.x,t.y,.8,dt);else m.d8=dir8(scrAng(Math.cos(a),Math.sin(a)));break}
      case'ghost':if(m.cd2<=0&&dd<9){m.cd2=6.5;burstAt(m.x,m.y,0x8affff,18,50);const ba=(P.lastMove??a)+Math.PI;let nx=P.x+Math.cos(ba)*1.6,ny=P.y+Math.sin(ba)*1.6;if(solidAt(M,nx,ny)){nx=P.x-Math.cos(a)*1.6;ny=P.y-Math.sin(a)*1.6}if(!solidAt(M,nx,ny)){m.x=nx;m.y=ny}burstAt(m.x,m.y,0x8affff,18,50);sfx('blink');const a2=Math.atan2(P.y-m.y,P.x-m.x);teles.push({shape:'cone',x:m.x,y:m.y,a:a2,r:2.2,arc:1.6,t:0,dur:.55,team:'m'});m.wind={t:.55,dur:.55,fire:()=>{fx.push({type:'slash',x:m.x,y:m.y,a:a2,r:2.1,t:0,life:.2,arc:1.6});if(dist(m,P)<2.2+P.r&&angDiff(Math.atan2(P.y-m.y,P.x-m.x),a2)<.85)hurtPlayer(1.5,m,{knock:2})}};m.face=a2}
        else if(m.cd3<=0&&dd>2.5){m.cd3=2.8;W(.4,()=>{shoot('m',m.x,m.y,Math.atan2(P.y-m.y,P.x-m.x),6,'arcane',.9,{},m);sfx('bolt')},'cast')}
        else if(dd<1.5&&m.atkCD<=0){m.atkCD=1.6;teles.push({shape:'cone',x:m.x,y:m.y,a,r:2,arc:1.5,t:0,dur:.45,team:'m'});W(.45,()=>{if(dist(m,P)<2+P.r&&angDiff(Math.atan2(P.y-m.y,P.x-m.x),a)<.8)hurtPlayer(1.2,m,{})})}
        else mobMoveTo(m,t.x,t.y,1,dt);break}}
  if(m.moving){m.anim='walk';m.animT+=dt;m.frame=Math.floor(m.animT*(d.ai==='boar'?11:10))%8}else if(!m.wind&&m.atkT<=0){m.anim='idle';m.frame=Math.floor(T*1.5+m.id)%2}}
function updTeles(dt){for(let i=teles.length-1;i>=0;i--){const t=teles[i];t.t+=dt;if(t.t>=t.dur){teles.splice(i,1);if(t.fire)t.fire()}}}
// ---------- NPCs, villagers, bots ----------
function spawnNpcs(){for(const id in MAPS){const m=MAPS[id];for(const d of m.npcDefs||[])npcs.push(Object.assign({type:'npc',m:id,r:.3,d8:0,anim:'idle',frame:0,animT:0,bub:null,ambT:rnd(8,25),hx:d.x,hy:d.y,ri:0,path:[],rp:0},d,{look:Object.assign({},d.look)}))}}
function updNpc(n,dt){if(n.bub&&(n.bub.t-=dt)<=0)n.bub=null;n.moving=false;
  if(n.role==='villager'){const night=isNight();const target=night?MAPS.world.homes[n.home]:n.route[n.ri];if(!n.wait||n.wait<=0){const dd=Math.hypot(n.x-target[0],n.y-target[1]);if(dd>.3){steer(n,target[0],target[1],1.6,dt,false)}else if(night){n.indoor=1}else{n.wait=rnd(2,6);n.ri=(n.ri+1)%n.route.length}}else n.wait-=dt;if(!night)n.indoor=0}
  if(n.moving){n.anim='walk';n.animT+=dt*.4;n.frame=Math.floor(n.animT*10)%8}else{n.anim='idle';n.frame=Math.floor(T*1.4+n.hx)%2;if(n.role!=='villager'&&P&&P.map===n.m&&dist(n,P)<4)n.d8=dir8(scrAng(P.x-n.x,P.y-n.y))}
  n.ambT-=dt;if(n.ambT<=0){n.ambT=rnd(16,34);if(P&&P.map===n.m&&dist(n,P)<9&&!n.hidden&&!n.indoor){const L=NPC_AMB[n.role];if(L)say(n,pick(L),4)}}}
const NPC_AMB={bank:['Seu ouro está seguro comigo.','Cuidado lá fora. O banco não guarda vidas.'],temple:['Que a luz te guie.','Feridos, venham ao templo.'],shop:['Poções fresquinhas!','Pergaminho de Retorno, nunca saia sem um.'],smith:['Aço bom não se faz com pressa.','*clang* *clang*'],hunter:['O bosque está estranho ultimamente.','Já viu um lobo do tamanho de um cavalo?','As flores que brilham crescem perto das pedras velhas. Minha avó dizia que eram lanternas pros mortos.'],guard:['Estrada leste aberta.','À noite os lobos ficam ousados.'],villager:['Bom dia!','Viu meu gato por aí?','Dizem que o cemitério é assombrado...','O pão da taverna é o melhor da região.'],tome:['Obrigado por me salvar!']};
function spawnBots(){const W=MAPS.world;const zones=[[14,2,42,11],[32,26,43,60],[49,24,62,60],[4,34,29,60],[33,30,42,58],[14,14,28,28]];BOT_NAMES.forEach(([name,cls],i)=>{const z=zones[i];let x,y;for(let k=0;k<60;k++){x=rint(z[0],z[2]);y=rint(z[1],z[3]);if(walkable(W,x,y))break}
  const gear=START[cls];const fake={eq:{},skin:i%4,hairC:(i*3)%5,hs:i%3?'short':'long',capeC:(i*2)%5,beard:i===3};for(const [sl,id] of Object.entries(gear))fake.eq[sl]={id};if(i===2)fake.eq.peito={id:'cota'};if(i===4)fake.eq.cabeca={id:'elmo'};
  bots.push({type:'bot',name,cls,m:'world',look:playerLook(fake),x:x+.5,y:y+.5,r:.3,zone:z,d8:0,anim:'idle',frame:0,animT:0,atkT:0,atkCD:0,target:null,path:[],rp:0,wT:0,lv:[8,6,12,4,9,3][i],town:i===5})})}
function updBot(b,dt){b.atkCD-=dt;b.atkT-=dt;if(b.bub&&(b.bub.t-=dt)<=0)b.bub=null;b.moving=false;const W=MAPS.world;
  if(b.target&&(b.target.dying||b.target.dead))b.target=null;
  if(!b.target){b.wT-=dt;if(b.wT<=0){b.wT=rnd(1.5,4);let best=null,bd=9;if(!b.town)for(const m of mobs){if(m.m!=='world'||m.dying||m.def.boss||m.def.elite||m.def.ai==='dummy'||m.target===P)continue;if(m.x<b.zone[0]||m.x>b.zone[2]+1||m.y<b.zone[1]||m.y>b.zone[3]+1)continue;const d=dist(b,m);if(d<bd){bd=d;best=m}}
      if(best&&Math.random()<.6)b.target=best;else{b.gx=rint(b.zone[0],b.zone[2])+.5;b.gy=rint(b.zone[1],b.zone[3])+.5;if(!walkable(W,Math.floor(b.gx),Math.floor(b.gy)))b.gx=null}}
    if(b.gx!=null){steer(b,b.gx,b.gy,2.8,dt,false);if(Math.hypot(b.x-b.gx,b.y-b.gy)<.4)b.gx=null}}
  else{const t=b.target,dd=dist(b,t),range=b.cls==='g'||b.cls==='l'?1.4:5;if(dd<=range&&los(W,b,t)){b.d8=dir8(scrAng(t.x-b.x,t.y-b.y));if(b.atkCD<=0){b.atkCD=rnd(.9,1.3);b.atkT=.3;b.atkAnim=b.cls==='g'||b.cls==='l'?'atk':b.cls==='a'?'bow':'cast';const a=Math.atan2(t.y-b.y,t.x-b.x);if(b.cls==='g'||b.cls==='l'){if(t.m===M.id)fx.push({type:'slash',x:b.x,y:b.y,a,r:1.4,t:0,life:.16,arc:1.8,dim:1});later(.08,()=>botHit(t,b,1))}else{const sm=M;M=W;shoot('b',b.x,b.y,a,b.cls==='a'?14:10,b.cls==='a'?'arrow':'bolt',1,{},b);M=sm;projs[projs.length-1].m='world'}}}else steer(b,t.x,t.y,2.8,dt,false)}
  if(b.atkT>0){b.anim=b.atkAnim;b.frame=clamp(Math.floor((1-b.atkT/.3)*4),0,3)}else if(b.moving){b.anim='walk';b.animT+=dt*.7;b.frame=Math.floor(b.animT*10)%8}else{b.anim='idle';b.frame=Math.floor(T*1.5)%2}}
function botSay(b,txt){if(!b)return;say(b,txt,4.5);log(`${b.name}: ${txt}`,'bot')}
// ---------- interactions & dialogs ----------
function openBossChest(e){e.opened=true;e.obj.cv=ART.chestOpen.cv;sfx('chest');burstAt(e.x,e.y,0xffd23a,30,80);const g=rint(160,360);loots.push({gold:g,x:e.x+.4,y:e.y+.4,m:M.id,t:120,age:0});
  const lvCap=Math.max(6,P.lv+3),pool=DROP_POOL.filter(id=>BASES[id].lv<=lvCap),mine=pool.filter(id=>!BASES[id].cls||BASES[id].cls===P.cls);
  for(let i=0;i<2;i++){const id=pick(Math.random()<.75&&mine.length?mine:pool);loots.push({item:makeItem(id,Math.max(1,rollRar(2.5))),x:e.x+rnd(-.6,.8),y:e.y+rnd(-.6,.6),m:M.id,t:180,age:0})}
  const bd=M.boss&&MOBS[M.boss[0]];if(bd&&Math.random()<.35){const eqs=bd.drops.filter(([id])=>BASES[id]&&BASES[id].t==='eq');if(eqs.length){const [id]=pick(eqs);loots.push({item:makeItem(id,2),x:e.x+.2,y:e.y-.4,m:M.id,t:180,age:0})}}
  loots.push({item:makeItem('pot_hp2',0),x:e.x-.4,y:e.y+.2,m:M.id,t:120,age:0});log('O baú do chefe se abre: ouro, equipamento e poções!','loot','#ffa53a');toast('Baú do chefe','Recompensa pela vitória')}
function interactables(){const out=[];for(const n of npcs)if(n.m===M.id&&!n.hidden&&!n.indoor)out.push({kind:'npc',e:n,x:n.x,y:n.y,label:'Falar com '+n.n.split(',')[0]});for(const a of M.acts){const label=a.label||{sealed:'Examinar porta selada',grave:'Examinar lápide',cave:'Entrar na Toca dos Goblins',exit:'Sair',chest:'Abrir baú'}[a.kind];if(a.kind==='chest'&&P.flags.chests[a.id])continue;if(a.needQ&&!(P.q[a.needQ]>=1))continue;if(a.kind==='bchest'&&(!M.bossDown||a.opened))continue;if(a.kind==='mine'&&a.t>0)continue;out.push({kind:a.kind,e:a,x:a.x,y:a.y,label})}return out}
function nearestInteract(){let best=null,bd=1.9;for(const it of interactables()){const d=Math.hypot(it.x-P.x,it.y-P.y);if(d<bd){bd=d;best=it}}return best}
function interact(it){if(!it||P.dead)return;const e=it.e;
  if(it.kind==='npc'){talk(e);return}
  if(it.kind==='mine'){mineNode(e);return}
  if(it.kind==='bchest'){openBossChest(e);return}
  if(it.kind==='cave'){changeMap('dungeon',MAPS.dungeon.spawnPt[0],MAPS.dungeon.spawnPt[1]);return}
  if(it.kind==='exit'){const to=e.to||'world',at=e.at||MAPS.world.caveOut;changeMap(to,at[0],at[1]);return}
  if(it.kind==='enter'){const at=e.at||MAPS[e.to].spawnPt;if(e.warp){burstAt(P.x,P.y,0x9ad8ff,26,70);sfx('blink');P.warpCD=1.4}changeMap(e.to,at[0],at[1]);if(e.msg)log(e.msg,'sys');return}
  if(it.kind==='chest'){P.flags.chests[e.id]=1;e.obj.cv=ART.chestOpen.cv;const g=rint(60,140);loots.push({gold:g,x:e.x+.4,y:e.y+.4,m:M.id,t:90,age:0});const pool=DROP_POOL.filter(id=>BASES[id].lv<=Math.max(5,P.lv+1));const id=pick(pool.filter(i=>!BASES[i].cls||BASES[i].cls===P.cls));loots.push({item:makeItem(id,Math.max(1,rollRar(1))),x:e.x+.6,y:e.y-.2,m:M.id,t:120,age:0});sfx('chest');log('Você encontrou um baú escondido!','sys');if(e.id==='bosque'&&!countItem('pagina')&&!P.flags.santuario){addItem(makeItem('pagina'));P.q.santuario=Math.max(P.q.santuario||0,1);log('Dentro do baú há uma página rasgada de diário. (Veja no inventário.)','sys');later(.6,()=>dlg('Página Rasgada',BASES.pagina.d,[{l:'Guardar'}]))}if(e.id==='santuario')P.q.santuario=Math.max(P.q.santuario||0,2);gainExp(40,1);save();return}
  if(it.kind==='sealed'){if(P.flags.sealed){dlg('Porta selada','A sala atrás da porta está vazia agora. Só restou o cheiro de incenso velho.',[]);return}
    if(!countItem('chave_osso')){dlg('Porta selada','Uma porta de ferro sob o templo, com um crânio entalhado no lugar da fechadura. Ninguém na vila admite saber o que tem do outro lado.',[]);if(!P.q.porta){P.q.porta=1;log('Descoberta: A Porta Selada.','sys');uiDirty=1}return}
    takeItem('chave_osso',1);P.flags.sealed=1;P.q.porta=2;sfx('chest');const pool=DROP_POOL.filter(id=>BASES[id].lv<=P.lv+2&&(!BASES[id].cls||BASES[id].cls===P.cls));loots.push({item:makeItem(pick(pool),3),x:e.x+.6,y:e.y+.6,m:M.id,t:300,age:0});loots.push({gold:400,x:e.x+.3,y:e.y+.9,m:M.id,t:300,age:0});gainExp(500,1);
    dlg('Porta selada','A Chave de Osso gira sozinha. Lá dentro, um relicário do Abade: ouro, um equipamento antigo e um diário. A última página diz: "o Rei Goblin me prometeu os ossos de Pedravale". Então os dois estavam juntos...',[{l:'Guardar tudo',pri:1}]);save();return}
  if(it.kind==='grave'){if(P.q.tumulo>=3){dlg('Lápide sem nome','A terra está calma agora. Alguém deixou flores frescas sobre a pedra.',[]);return}
    if(isNight()){if(mobs.some(m=>m.kind==='guardiao'&&!m.dying)){return}P.q.tumulo=2;dlg('Lápide sem nome','Um frio sobe pela sua espinha. Uma voz rouca sussurra: "Lembre-se de mim..." A terra se abre.',[{l:'Preparar-se',pri:1}]);const g=spawnMob('guardiao',M,null,[e.x+1.2,e.y+.4]);g.target=P;sfx('roar');log('Descoberta: O Túmulo Sem Nome.','sys')}
    else{if(!P.q.tumulo){P.q.tumulo=1;log('Descoberta: O Túmulo Sem Nome.','sys');uiDirty=1}dlg('Lápide sem nome','A pedra não tem nome, só uma frase meio apagada: "...vigia até que o lembrem". A terra em volta parece mexida. Talvez algo aconteça quando a vila dormir.',[])}}}
function talk(n){const nm=n.n;if(n.role!=='villager')n.d8=dir8(scrAng(P.x-n.x,P.y-n.y));
  switch(n.role){
    case'bank':dlg(nm,'Bem-vindo ao Banco de Pedravale. O que você guardar aqui fica seguro, mesmo que você caia lá fora.',[{l:'Abrir cofre',pri:1,f:openBank},{l:'Algum boato?',f:()=>dlg(nm,'Ninguém sabe quem está na lápide sem nome do cemitério. Os coveiros juram que, à noite, a terra se mexe sozinha. Eu não pergunto, só guardo ouro.',[])},{l:'Até logo'}]);break;
    case'temple':{const d=D();P.hp=d.maxHp;P.mp=d.maxMp;burstAt(P.x,P.y,0xfff0b0,20,40);sfx('heal');dlg(nm,'Que a luz te restaure. Se você cair lá fora, despertará aqui, no templo. Também preparo poções e elixires, se você trouxer os ingredientes.',[{l:'Alquimia',pri:1,f:()=>alchemyMenu(nm)},{l:'Obrigado'}]);break}
    case'refine':refineMenu(nm);break;
    case'evo':evoMenu(nm);break;
    case'pets':petMenu(nm);break;
    case'shop':openShop('lia',nm);break;
    case'rshop':openShop(n.shop,nm);break;
    case'quest':rqTalk(n);break;
    case'talker':dlg(nm,pick(n.lines||['...']),[{l:'Até mais'}]);break;
    case'travel':{const here=CITIES.find(c=>c.map===n.m);dlg(nm,`Posso abrir um portal para qualquer cidade. A passagem custa ${TRAVEL_COST} ouro. Para onde?`,[...CITIES.filter(c=>c!==here).map(c=>({l:`${c.n} — ${MAPS[c.map].name} (Nv ${({world:'1–11',gelo:'13–24',japao:'23–34',deserto:'33–44',selva:'41–52'})[c.map]||'?'})`,pri:0,f:()=>travelTo(c)})),{l:'Agora não'}]);break}
    case'smith':{const q=P.q.filho;const opts=[{l:'Ver mercadorias',pri:1,f:()=>openShop(P.q.filho>=3?'brunoMestre':'bruno',nm)},{l:'Refinar equipamento',f:()=>refineMenu(nm)}];
      if(q===0)dlg(nm,'Meu filho Tomé foi buscar lenha no bosque há três dias e não voltou. Os guardas dizem que viram goblins perto do rio... Se você for para aqueles lados, procure por ele. Por favor.',[{l:'Vou procurar',pri:1,f:()=>{P.q.filho=1;log('Missão: O Filho do Ferreiro','sys');sfx('ok');uiDirty=1}},...opts,{l:'Agora não'}]);
      else if(q===1)dlg(nm,'Nenhuma notícia do Tomé ainda? Dizem que os goblins levam prisioneiros para a toca deles, depois do rio.',[...opts,{l:'Continuo procurando'}]);
      else if(q===2){P.q.filho=3;const it=makeItem('martelo');if(!addItem(it))loots.push({item:it,x:P.x,y:P.y,m:M.id,t:300,age:0});gainExp(350,1);P.gold+=150;sfx('lvl');log('Recompensa: Martelo do Aprendiz, 150 ouro. Bruno agora vende o estoque do mestre.','loot','#ffa53a');uiDirty=1;
        dlg(nm,'Tomé chegou em casa! Eu nem sei como agradecer. Fique com isto: o primeiro martelo que ele forjou. E daqui pra frente, minha forja inteira está aberta pra você, inclusive o estoque do mestre.',[...opts,{l:'Obrigado'}])}
      else dlg(nm,'O Tomé já voltou a martelar. Vai ser um ferreiro melhor que o pai.',[...opts,{l:'Até mais'}]);break}
    case'hunter':{const q=P.q.cacada;if(q===0)dlg(nm,'Trinta invernos caçando nesse bosque, e um lobo eu nunca peguei: um alfa enorme, com uma cicatriz no flanco. Ele quase nunca aparece, e quando aparece, a matilha fica mais ousada. Traga a pele dele e eu te dou algo que vale a caçada.',[{l:'Aceito',pri:1,f:()=>{P.q.cacada=1;log('Missão: A Última Caçada','sys');sfx('ok');uiDirty=1}},{l:'Talvez depois'}]);
      else if(q===1){if(countItem('pele_alfa')){takeItem('pele_alfa',1);P.q.cacada=2;const id=P.cls==='a'?'arco_cacador':'amuleto_cacador';const it=makeItem(id);if(!addItem(it))loots.push({item:it,x:P.x,y:P.y,m:M.id,t:300,age:0});gainExp(400,1);sfx('lvl');log(`Recompensa: ${BASES[id].n}.`,'loot','#ffa53a');uiDirty=1;dlg(nm,'É ele. Essa cicatriz fui eu que fiz, muitos anos atrás. A caçada terminou... Fique com isto. Você merece mais do que eu.',[{l:'Obrigado'}])}else dlg(nm,'O alfa anda pelo Bosque de Vellmor, a leste do rio... ou a oeste, depende do humor dele. Ouça os uivos.',[{l:'Certo'}])}
      else dlg(nm,'O bosque parece mais calmo sem o velho alfa. Estranho sentir falta de um inimigo.',[{l:'Até mais'}]);break}
    case'guard':{const tips=['As Terras Goblins ficam depois do rio. Você pode entrar. Mas talvez não consiga voltar.','Javalis avisam antes de investir: eles param e bufam. Saia da linha e deixe que batam na pedra.','O goblin de escudo defende tudo pela frente. Vá pelos lados ou use algo que quebre a guarda.','Arqueiros goblins miram antes de soltar a flecha. Dash na hora certa e a flecha passa.','À noite, as feras enxergam melhor que você. E dizem que o cemitério não dorme.','O banco do Osvaldo guarda o que você não quer perder.','A porta do mausoléu no cemitério não está trancada. Ninguém que desceu voltou falando muito.','No fim da estrada leste fica o Forte Goblin. O Rei deles nunca sai de lá.'];n.tip=(n.tip||0)+1;dlg(nm,tips[(n.tip-1)%tips.length],[{l:'Entendido'}]);break}
    case'tome_cage':{if(P.q.filho>=2){dlg(nm,'Vou correndo pra casa!',[]);break}P.q.filho=2;n.hidden=1;npcs.find(x=>x.id==='tome').hidden=0;burstAt(n.x,n.y,0xfff0b0,16,40);sfx('ok');uiDirty=1;dlg(nm,'Você veio! O Chefe Goblin me pegou no bosque e queria que eu consertasse as armas deles. Vou fugir pela saída enquanto eles estão distraídos. Diga ao meu pai que estou indo pra casa!',[{l:'Vá, rápido!',pri:1}]);break}
    case'tome':dlg(nm,'Obrigado por me tirar daquela jaula! Meu pai tem uma coisa pra você.',[{l:'De nada'}]);break;
    default:dlg(nm,pick(['Bom dia, aventureiro!','Dizem que os goblins estão mais ousados este ano.','Já provou o pão da taverna?','Meu avô dizia que o rio tinha peixes de ouro.']),[{l:'Até mais'}])}}
// ---------- world flow ----------
function unstick(m,e){if(!blockedAt(m,e.x,e.y,e.r||.3))return;for(let r=.5;r<6;r+=.5)for(let a=0;a<6.28;a+=.4){const x=e.x+Math.cos(a)*r,y=e.y+Math.sin(a)*r;if(!blockedAt(m,x,y,e.r||.3)){e.x=x;e.y=y;return}}}
function blockedAt(m,x,y,r){return solidAt(m,x-r,y-r)||solidAt(m,x+r,y-r)||solidAt(m,x-r,y+r)||solidAt(m,x+r,y+r)}
function changeMap(id,x,y){if(bossActive&&bossActive.m===M.id&&id!==M.id)resetBoss();P.map=id;M=MAPS[id];P.x=x;P.y=y;unstick(M,P);P.kx=P.ky=0;P.vx=P.vy=0;P.stun=0;P.dash=null;projs.length=0;teles.length=0;cam.init=false;lastRegion=null;sfx('door');P.fish=null;if(pet){pet.x=P.x;pet.y=P.y}onMapStats(id);save()}
let lastRegion=null,lvlFx=0;
function regionAt(m,x,y){for(const r of m.regions)if(x>=r.r[0]&&x<=r.r[2]+1&&y>=r.r[1]&&y<=r.r[3]+1)return r;return m.regions[m.regions.length-1]}
function closeCircle(){const w=MAPS.world,c=w.circle;if(!c||!c.open)return;c.open=false;w.objs=w.objs.filter(o=>!o.portal||o.keep);w.acts=w.acts.filter(a=>!(a.kind==='enter'&&a.to==='santuario'));for(const o of c.plants)o.plant.t=0;if(P)P.flags.santuario=0;log('O portal do círculo de pedras se fechou. As plantas apagaram.','sys')}
function openCircle(quiet){const w=MAPS.world,c=w.circle;if(!c||c.open)return;c.open=true;const o=prop(w,38,36,ART.portalBase,{block:null,noShadow:1,portal:1,light:{dx:0,dy:-28,r:115,cold:1}});o.k=74.2;w.acts.push({kind:'enter',to:'santuario',x:38.6,y:37,label:'Atravessar o portal',msg:'O portal puxa você como água fria. Do outro lado, musgo e silêncio.'});w.chunks.clear();if(!quiet){shake=.4;sfx('victory');log('As pedras vibram e um portal se abre no centro do círculo. Ele não vai durar para sempre: se você cair, ele se fecha.','sys');toast('Um portal se abriu','Se você morrer, o portal se fecha')}P.flags.santuario=1;if(P.q.santuario<2)P.q.santuario=2;uiDirty=1;save()}
function updWorld(dt){TIME=(TIME+dt/CFG.dayLength)%1;for(const o of M.plants)if(o.plant.t>0)o.plant.t-=dt;
  {const c=MAPS.world.circle;if(c&&!c.open&&M.id==='world'&&c.plants.every(o=>o.plant.t>0)){if(isNight())openCircle();else if(!c.hinted||T-c.hinted>20){c.hinted=T;toast('As pedras esperam','Nada acontece... talvez sob a lua');log('As flores-lume brilham juntas, mas as pedras continuam frias. Talvez precise ser à noite.','npc')}}}
  weather.t-=dt;if(weather.t<=0){weather.t=rnd(120,260);weather.target=weather.target>0?(Math.random()<.35?rnd(.4,1):0):(Math.random()<.6?rnd(.5,1):0);if(weather.target>0)log('Nuvens pesadas cobrem o céu.','sys')}weather.rain+=(weather.target-weather.rain)*Math.min(1,dt*.3);
  for(let i=timers.length-1;i>=0;i--){timers[i].t-=dt;if(timers[i].t<=0){const f=timers[i].fn;timers.splice(i,1);f()}}
  for(let i=respawnQ.length-1;i>=0;i--){const r=respawnQ[i];r.t-=dt;if(r.t<=0){respawnQ.splice(i,1);spawnMob(r.kind,MAPS[r.m],r.rect,r.at)}}
  for(let i=loots.length-1;i>=0;i--){loots[i].age+=dt;if((loots[i].t-=dt)<=0)loots.splice(i,1)}
  alphaT-=dt;if(alphaT<=0){alphaT=rnd(70,130);if(!mobs.some(m=>m.kind==='lobo_alfa'&&!m.dying)&&Math.random()<(isNight()?.7:.35)){spawnMob('lobo_alfa',MAPS.world,[33,30,43,60]);log('Um uivo longo e grave ecoa pelo Bosque de Vellmor...','sys')}}
  chatT-=dt;if(chatT<=0){chatT=rnd(10,24);botSay(pick(bots),pick(BOT_LINES))}
  const r=regionAt(M,P.x,P.y);if(r!==lastRegion){lastRegion=r;regionBanner(r);const key=M.id+r.n;if(!P.flags.seen[key]){P.flags.seen[key]=1;if(r.dg>0){const xp=CFG.discoverXp[r.dg]||10;later(.8,()=>{gainExp(xp,1);log(`Região descoberta: ${r.n} (+${xp} XP)`,'sys')})}}}}
let alphaT=40,chatT=12;
