// ===================== rendering =====================
const cv=$('#view'),vx=cv.getContext('2d');const buf=document.createElement('canvas');buf.width=buf.height=8;const b=buf.getContext('2d',{willReadFrequently:true});const [lc,lx]=mk(8,8);
let DPR=1,ZOOM=2,K=2,BW=8,BH=8,sx0=0,sy0=0,userZoom=false;const cam={x:0,y:0,init:false};
const ZOOMS=[1,1.5,2,2.5,3];
function resize(){DPR=Math.min(2,window.devicePixelRatio||1);cv.width=Math.round(innerWidth*DPR);cv.height=Math.round(innerHeight*DPR);cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';if(!userZoom)ZOOM=innerWidth<760?1.5:innerWidth>=1600?3:2;K=Math.max(1,Math.round(ZOOM*DPR));BW=Math.ceil(cv.width/K);BH=Math.ceil(cv.height/K);buf.width=BW;buf.height=BH;lc.width=BW;lc.height=BH;b.imageSmoothingEnabled=false;vx.imageSmoothingEnabled=false}
function setZoom(dz){let i=ZOOMS.indexOf(ZOOM);if(i<0)i=2;ZOOM=ZOOMS[clamp(i+dz,0,ZOOMS.length-1)];userZoom=true;resize()}
const ICONC={};function iconCanvas(id){return ICONC[id]||(ICONC[id]=itemIcon(...BASES[id].ic))}
function burstAt(tx,ty,col,n,spd){const [wx,wy]=wpx(tx,ty);const c=typeof col==='number'?hex(col):col;for(let i=0;i<n;i++){const a=Math.random()*6.283,s=spd*rnd(.3,1);fx.push({type:'px',x:wx,y:wy-10,vx:Math.cos(a)*s,vy:Math.sin(a)*s*.6-20,g:90,t:0,life:rnd(.3,.65),col:c})}}
function ghostFx(e,col){const fr=entFrame(e,e.d8,e.anim,e.frame);const [wx,wy]=wpx(e.x,e.y);fx.push({type:'ghost',cv:fr.cv,x:wx-fr.ax,y:wy-fr.ay-(e.z||0),t:0,life:.25,col})}
function addText(e,txt,col,big){const [wx,wy]=wpx(e.x,e.y);texts.push({wx:wx+rnd(-6,6),wy:wy-38,txt:String(txt),col,t:0,life:big?1.4:1,vx:rnd(-18,18),big:!!big})}
function iso(tx,ty){const [wx,wy]=wpx(tx,ty);return[wx-sx0,wy-sy0]}
const FLAMES={fire:['#fff4c0','#ffc04a','#ff6a1a','#a8261a','#ffb04a'],ghost:['#e8fff8','#8affd8','#3ad0b0','#1a6a7a','#8affd8']};
function drawPortal(e){const x=Math.round(e.wx-sx0),y=Math.round(e.wy-sy0)-30,C=['#f4fbff','#bfe8ff','#8ab0ff','#a46ae0','#5a3aa8'];b.save();const g=b.createRadialGradient(x,y,2,x,y,22);g.addColorStop(0,'rgba(10,8,30,.95)');g.addColorStop(.7,'rgba(40,30,110,.75)');g.addColorStop(1,'rgba(90,80,200,0)');b.fillStyle=g;b.beginPath();b.ellipse(x,y,15,26,0,0,7);b.fill();
  b.lineWidth=2;for(let i=0;i<5;i++){b.setLineDash([5+i,4]);b.lineDashOffset=(i%2?1:-1)*T*(30+i*8);b.strokeStyle=C[i];b.globalAlpha=.9-i*.12;b.beginPath();b.ellipse(x,y,15-i*2.4,26-i*4.2,0,0,7);b.stroke()}b.setLineDash([]);b.globalAlpha=1;
  for(let i=0;i<6;i++){const a=T*1.6+i*1.05,r=.35+.3*((T*.7+i*.37)%1);b.fillStyle=i%2?'#ffffff':'#bfe8ff';b.fillRect(Math.round(x+Math.cos(a)*15*r),Math.round(y+Math.sin(a)*26*r),1,1)}b.restore();
  if(Math.random()<.35)fx.push({type:'px',x:e.wx+rnd(-14,14),y:e.wy-rnd(6,50),vx:rnd(-4,4),vy:rnd(-24,-8),g:0,t:0,life:rnd(.5,1),col:pick(['#bfe8ff','#a46ae0','#ffffff'])})}
function drawFlame(bx,by,sz,seed,pal){const F=FLAMES[pal||'fire'];bx=Math.round(bx);by=Math.round(by);for(let i=-sz;i<=sz;i++){const fall=1-Math.abs(i)/(sz+1),h=Math.max(1,Math.round(sz*2.6*fall*(.55+.7*vn(i*.9+seed,T*7,4))));for(let j=0;j<h;j++){const f=j/h;b.fillStyle=Math.abs(i)<sz*.4&&f<.4?F[0]:f<.45?F[1]:f<.8?F[2]:F[3];b.fillRect(bx+i,by-j,1,1)}}if(Math.random()<.06*sz)fx.push({type:'px',x:bx+sx0+rnd(-sz,sz),y:by+sy0-sz*2,vx:rnd(-8,8),vy:rnd(-40,-18),g:0,t:0,life:rnd(.6,1.3),col:F[4],glow:1})}
function teleShape(t,scale){const pts=[];if(t.shape==='circle'){const n=28;for(let i=0;i<n;i++){const a=i/n*6.283;pts.push(iso(t.x+Math.cos(a)*t.r*scale,t.y+Math.sin(a)*t.r*scale))}}
  else if(t.shape==='cone'){pts.push(iso(t.x,t.y));const n=16;for(let i=0;i<=n;i++){const a=t.a-t.arc/2+t.arc*i/n;pts.push(iso(t.x+Math.cos(t.a-t.arc/2+t.arc*i/n)*t.r*scale,t.y+Math.sin(a)*t.r*scale))}}
  else{const ca=Math.cos(t.a),sa=Math.sin(t.a),hw=t.w/2,L=t.len*scale;for(const [u,v] of [[0,-hw],[L,-hw],[L,hw],[0,hw]])pts.push(iso(t.x+ca*u-sa*v,t.y+sa*u+ca*v))}return pts}
function poly(pts){b.beginPath();pts.forEach((p,i)=>i?b.lineTo(p[0],p[1]):b.moveTo(p[0],p[1]));b.closePath()}
function drawTele(t){const k=clamp(t.t/t.dur,0,1),mine=t.team==='p';const col=mine?'255,210,110':'235,50,35';
  b.globalAlpha=1;poly(teleShape(t,1));b.fillStyle=`rgba(${col},${t.thin?.12:.14+k*.08})`;b.fill();b.strokeStyle=`rgba(${col},${t.thin?.55:.8})`;b.lineWidth=1;b.stroke();
  if(!t.thin){poly(teleShape(t,t.shape==='line'?k:Math.max(.05,k)));b.fillStyle=`rgba(${col},${.18+k*.22})`;b.fill()}}
function lightsFor(o,nf,L){if(o.plant){const k=clamp(o.plant.t/8,0,1),r=k>0?50+k*110:(nf>.2||M.indoor?24:0);if(r)L.push([o.wx-sx0,o.wy-sy0-12,r*(k>0?.9+.1*Math.sin(T*9):1),2]);return}if(o.light){const on=!o.light.night||nf>.15;if(on){const f=o.light.night?Math.min(1,nf*1.6):1;L.push([o.wx+o.light.dx-sx0,o.wy+o.light.dy-sy0,o.light.r*(.95+.05*vn(T*4,o.wx,1))*(o.light.night?f:1),o.light.cold?2:1,o.light.a])}}if(o.light2){const l2=o.light2,on=!l2.night||nf>.15;if(on){const f=l2.night?Math.min(1,nf*1.6):1;L.push([o.wx+l2.dx-sx0,o.wy+l2.dy-sy0,l2.r*f,l2.cold?2:1,l2.a])}}
  if(o.wins&&nf>.2)for(const [dx,dy] of o.wins)L.push([o.wx+dx-sx0,o.wy+dy-sy0,64*Math.min(1,nf*1.5),1]);if(o.fire)L.push([o.wx+o.fire.dx-sx0,o.wy+o.fire.dy-sy0+6,90+o.fire.s*14,o.fire.pal==='ghost'?2:1])}
function render(dt){const m=M;b.globalCompositeOperation='source-over';b.globalAlpha=1;b.fillStyle=hex(m.bg);b.fillRect(0,0,BW,BH);
  let tx,ty;if(P&&state==='play'){[tx,ty]=wpx(P.x,P.y);ty-=22}else{[tx,ty]=wpx(21.5+Math.sin(T*.05)*5,21.5+Math.cos(T*.04)*4)}
  if(!cam.init){cam.x=tx;cam.y=ty;cam.init=true}cam.x+=(tx-cam.x)*Math.min(1,dt*4.5);cam.y+=(ty-cam.y)*Math.min(1,dt*4.5);
  const sh=shake>0?shake*7*CFG.shakeK:0;sx0=Math.round(cam.x-BW/2+rnd(-sh,sh));sy0=Math.round(cam.y-BH/2+rnd(-sh,sh)*.7);
  // ground
  let budget=state==='intro'?1:3;const c0=Math.floor(sx0/CH),c1=Math.floor((sx0+BW)/CH),r0=Math.floor(sy0/CH),r1=Math.floor((sy0+BH)/CH);
  for(let cy=r0;cy<=r1;cy++)for(let cx=c0;cx<=c1;cx++){let ch=getChunk(m,cx,cy,false);if(!ch&&budget>0){ch=getChunk(m,cx,cy,true);budget--}if(ch)b.drawImage(ch,cx*CH-sx0,cy*CH-sy0);else{b.fillStyle=m.id==='world'?'#4a6e36':'#0b0a10';b.fillRect(cx*CH-sx0,cy*CH-sy0,CH,CH)}}
  if(budget>0)for(let cy=r0-1;cy<=r1+1&&budget>0;cy++)for(let cx=c0-1;cx<=c1+1&&budget>0;cx++)if(!getChunk(m,cx,cy,false)){getChunk(m,cx,cy,true);budget--}
  const nf=nightF();
  if(m.id==='world'&&Math.random()<.5){const wt=m.waterTiles[Math.floor(Math.random()*m.waterTiles.length)];const [wx,wy]=wpx(wt[0]+Math.random(),wt[1]+Math.random());if(wx>sx0&&wy>sy0&&wx<sx0+BW&&wy<sy0+BH)fx.push({type:'spark',x:wx,y:wy,t:0,life:.6})}
  for(const t of teles)drawTele(t);
  for(const z of zones)if(z.m===m.id){const k=Math.min(1,z.t),[zx,zy]=iso(z.x,z.y),rx=z.r*32*1.41,ry=z.r*16*1.41;b.fillStyle=`rgba(255,230,140,${.12*k})`;b.strokeStyle=`rgba(255,240,170,${.75*k})`;b.beginPath();b.ellipse(zx,zy,rx,ry,0,0,7);b.fill();b.stroke();b.beginPath();b.ellipse(zx,zy,rx*(.5+.5*((T*.8)%1)),ry*(.5+.5*((T*.8)%1)),0,0,7);b.stroke()}
  for(const t of traps){const [x,y]=iso(t.x,t.y);b.strokeStyle=t.arm>0?'#8a7a5a':'#c8b090';b.lineWidth=1;b.beginPath();b.ellipse(x,y,9,4.5,0,0,7);b.stroke();for(let i=-6;i<=6;i+=3){b.fillStyle='#d8d0c0';b.fillRect(Math.round(x+i),Math.round(y-2-Math.abs(i)*.2),1,2)}}
  // gather drawables
  const L=[],list=[];const vx0=sx0-40,vy0=sy0-40,vx1=sx0+BW+40,vy1=sy0+BH+120;
  for(const o of m.objs){if(o.bb[2]<vx0||o.bb[0]>vx1||o.bb[3]<vy0||o.bb[1]>vy1)continue;list.push([o.k,0,o]);lightsFor(o,nf,L)}
  const vis=e=>{const [wx,wy]=wpx(e.x,e.y);return wx>vx0&&wx<vx1&&wy>vy0&&wy<vy1};
  for(const e of mobs)if(e.m===m.id&&!e.dead&&vis(e))list.push([e.x+e.y,1,e]);
  for(const e of npcs)if(e.m===m.id&&!e.hidden&&!e.indoor&&vis(e))list.push([e.x+e.y,1,e]);
  if(m.id==='world')for(const e of bots)if(vis(e))list.push([e.x+e.y,1,e]);
  for(const e of remotes.values())if(e.m===m.id&&e.look&&vis(e))list.push([e.x+e.y,1,e]);
  for(const g of remoteMobs())if(g.m===m.id&&g.look&&vis(g))list.push([g.x+g.y,1,g]);
  if(P&&state==='play')list.push([P.x+P.y,1,P]);for(const c of clones)if(c.m===m.id)list.push([c.x+c.y,1,c]);if(pet&&pet.m===m.id&&state==='play')list.push([pet.x+pet.y,1,pet]);for(const q of remotePets())if(q.m===m.id&&vis(q))list.push([q.x+q.y,1,q]);
  for(const l of loots)if(l.m===m.id&&vis(l))list.push([l.x+l.y-.25,2,l]);
  for(const p of projs)if(p.m===m.id)list.push([p.x+p.y,3,p]);
  list.sort((a,c)=>a[0]-c[0]);
  const pk=P?P.x+P.y:0,[ppx,ppy]=P?wpx(P.x,P.y):[0,0];const night=nf>.5;
  for(const [k,kind,e] of list){
    if(kind===0){const img=e.plant?(e.plant.t>0?e.plant.lit:e.cv):night&&e.cvN?e.cvN:e.cv;let al=1;if(e.tall&&P&&state==='play'&&k>pk+.3&&ppx>e.bb[0]&&ppx<e.bb[2]&&ppy-30>e.bb[1]&&ppy-30<e.bb[3]){al=.42}b.globalAlpha=al;b.drawImage(img,Math.round(e.wx-e.ox-sx0),Math.round(e.wy-e.oy-sy0));b.globalAlpha=1;
      if(e.portal)drawPortal(e);if(e.fire)drawFlame(e.wx+e.fire.dx-sx0,e.wy+e.fire.dy-sy0,e.fire.s,e.wx*.1,e.fire.pal);if(e.fires)for(const f of e.fires)drawFlame(e.wx+f[0]-sx0,e.wy+f[1]-sy0,1,e.wx+f[0],e.firePal);if(e.smoke&&Math.random()<.05)fx.push({type:'smoke',x:e.wx+e.smoke[0],y:e.wy+e.smoke[1],t:0,life:rnd(2,3.4),vx:rnd(4,9)})}
    else if(kind===1){drawEnt(e,L);if(e===P){refGlow(L);if(P.fish)drawFishLine(b)}}
    else if(kind===2)drawLoot(e,L);
    else drawProj(e,L)}
  // world particles
  for(const f of fx)drawFx(f,false);
  grade(nf);
  // lighting
  if(P&&state==='play'&&(nf>.05||m.indoor)){const [wx,wy]=wpx(P.x,P.y);L.push([wx-sx0,wy-sy0-14,m.indoor?100:70,0,m.indoor?.38:.16,1])}
  for(const p of projs)if(p.m===m.id&&(p.kind==='fire'||p.kind==='bolt'||p.kind==='arcane'||p.kind==='holy'||p.kind==='ice'||(p.o&&(p.o.el==='fire'||p.o.el==='frost'||p.o.el==='poison')))){const [x,y]=iso(p.x,p.y);{const w=p.kind==='fire'||(p.o&&p.o.el==='fire');L.push([x,y-10,w?80:50,w?1:2])}}
  for(const f of flies){const [x,y]=iso(f.x,f.y);const g=.5+.5*Math.sin(f.ph);if(g>.25)L.push([x,y-f.z,34*g,3])}
  for(const z of zones)if(z.m===m.id){const [x,y]=iso(z.x,z.y);L.push([x,y,110,1])}
  for(const f of fx)if((f.type==='whirl'&&f.el==='fire')||(f.type==='crack'&&f.el&&f.t<1)){const [x,y]=f.type==='whirl'?iso(f.x,f.y):iso(f.segs[0][3][0],f.segs[0][3][1]);L.push([x,y-8,f.type==='whirl'?110:80,f.el==='fire'?1:2])}
  for(const f of fx)if(f.type==='zap'&&f.t<.18){const [x,y]=iso(f.x,f.y);L.push([x,y-20,170,2])}
  for(const t of teles)if(t.team==='p'){const [x,y]=iso(t.x,t.y);L.push([x,y,60,1])}
  const dark=m.indoor?m.dark*.9:nf*.56+rainNow()*.08;
  if(dark>.01){lx.globalCompositeOperation='source-over';lx.clearRect(0,0,BW,BH);lx.fillStyle=m.indoor?`rgba(${m.darkCol||'14,8,26'},${dark})`:`rgba(8,12,34,${dark})`;lx.fillRect(0,0,BW,BH);lx.globalCompositeOperation='destination-out';
    for(const [x,y,r,,a,sf] of L){lx.globalAlpha=a??1;lx.drawImage(sf?LS.soft:LS.light,Math.round(x-r),Math.round(y-r*.62),Math.round(r*2),Math.round(r*1.24))}lx.globalAlpha=1;b.drawImage(lc,0,0)}
  b.globalCompositeOperation='lighter';for(const [x,y,r,g,a] of L){if(!g)continue;b.globalAlpha=(dark>.05?.62:.2)*(a??1);b.drawImage(g===3?LS.fly:g===2?LS.cold:LS.glow,x-r*.85,y-r*.55,r*1.7,r*1.1)}b.globalAlpha=1;for(const f of flies){const [x,y]=iso(f.x,f.y);const g=.5+.5*Math.sin(f.ph);if(g>.2){b.fillStyle=g>.7?'#f8ffc0':'#c8f070';b.fillRect(Math.round(x),Math.round(y-f.z),g>.7?2:1,g>.7?2:1)}}
  for(const f of fx)drawFx(f,true);b.globalCompositeOperation='source-over';
  if(!m.indoor&&m.climate==='snow')drawSnow(dt,.45+weather.rain*.55);else if(!m.indoor&&rainNow()>.02)drawRain(dt);if(VIG.w!==BW||VIG.h!==BH)buildVig();b.drawImage(VIG.c,0,0);
  // bars
  for(const g of remoteMobs()){if(g.m!==m.id||g.dying)continue;const [x,y]=iso(g.x,g.y);const w=g.champ||g.def.elite||g.def.boss?36:24;b.fillStyle='#0a080c';b.fillRect(Math.round(x-w/2)-1,Math.round(y+4),w+2,4);b.fillStyle='#7af0b0';b.fillRect(Math.round(x-w/2),Math.round(y+5),Math.max(0,Math.round(w*g.hpF)),2)}
  for(const e of mobs){if(e.m!==m.id||e.dead||e.dying||e.def.boss||e.def.ai==='dummy'||(e.hpShow<=0&&e!==hoverMob))continue;const [x,y]=iso(e.x,e.y);const w=e.def.elite||e.champ?36:24;b.fillStyle='#0a080c';b.fillRect(Math.round(x-w/2)-1,Math.round(y+4),w+2,4);b.fillStyle=e.def.elite||e.champ?'#e8a83a':'#d8403a';b.fillRect(Math.round(x-w/2),Math.round(y+5),Math.max(0,Math.round(w*e.hp/e.maxHp)),2)}
  if(P&&state==='play'&&!P.dead){const d=D(),[x,y]=iso(P.x,P.y);b.fillStyle='#0a080c';b.fillRect(Math.round(x-13),Math.round(y+4),28,6);b.fillStyle=P.hp/d.maxHp<.3?'#e8574a':'#5ad16a';b.fillRect(Math.round(x-12),Math.round(y+5),Math.round(26*P.hp/d.maxHp),2);b.fillStyle='#4a8ae8';b.fillRect(Math.round(x-12),Math.round(y+8),Math.round(26*P.mp/d.maxMp),1);
    if(P.cast){b.fillStyle='#fff0b0';b.fillRect(Math.round(x-12),Math.round(y-56),Math.round(26*(1-P.cast.t/3)),2)}}
  if(CFG.pixelFinish)pixelFinish();vx.imageSmoothingEnabled=false;vx.drawImage(buf,0,0,BW*K,BH*K);overlay()}
let hoverMob=null;
const OBOX=new WeakMap();function opaqueBox(cv){let r=OBOX.get(cv);if(r)return r;const d=cv.getContext('2d').getImageData(0,0,cv.width,cv.height).data;let x0=cv.width,y0=cv.height,x1=0,y1=0;for(let y=0;y<cv.height;y++)for(let x=0;x<cv.width;x++)if(d[(y*cv.width+x)*4+3]>40){if(x<x0)x0=x;if(x>x1)x1=x;if(y<y0)y0=y;if(y>y1)y1=y}r=[x0,y0,x1,y1];OBOX.set(cv,r);return r}
function drawIceBlock(gx,gy,fr,e){const ob=opaqueBox(fr.cv),by=gy-Math.round(e.z||0),w=Math.max(10,Math.round((ob[2]-ob[0])/2)+3),dp=Math.round(w*.55),top=by-fr.ay+ob[1]-3,hgt=Math.max(14,gy+2-top-dp/2),k=Math.min(1,e.frozenT/.4),wob=e.frozenT<.6?Math.round(Math.sin(T*60)):0;const x0=gx+wob,y0=gy+2;b.save();b.globalAlpha=.26*k;
  // left face, right face, top face (isometric prism)
  b.fillStyle='#8ad8f8';b.beginPath();b.moveTo(x0-w,y0-dp/2);b.lineTo(x0,y0);b.lineTo(x0,y0-hgt);b.lineTo(x0-w,y0-hgt-dp/2);b.closePath();b.fill();
  b.fillStyle='#5ab0e0';b.beginPath();b.moveTo(x0,y0);b.lineTo(x0+w,y0-dp/2);b.lineTo(x0+w,y0-hgt-dp/2);b.lineTo(x0,y0-hgt);b.closePath();b.fill();
  b.globalAlpha=.5*k;b.fillStyle='#e8faff';b.beginPath();b.moveTo(x0,y0-hgt);b.lineTo(x0+w,y0-hgt-dp/2);b.lineTo(x0,y0-hgt-dp);b.lineTo(x0-w,y0-hgt-dp/2);b.closePath();b.fill();
  b.globalAlpha=.9*k;b.strokeStyle='#ffffff';b.lineWidth=1;b.beginPath();b.moveTo(x0-w+.5,y0-dp/2);b.lineTo(x0-w+.5,y0-hgt-dp/2);b.lineTo(x0,y0-hgt-dp);b.lineTo(x0+w-.5,y0-hgt-dp/2);b.moveTo(x0+.5,y0);b.lineTo(x0+.5,y0-hgt);b.stroke();
  b.strokeStyle='rgba(255,255,255,.6)';b.beginPath();b.moveTo(x0-w*.6,y0-hgt*.3);b.lineTo(x0-w*.35,y0-hgt*.55);b.lineTo(x0-w*.5,y0-hgt*.7);b.moveTo(x0+w*.3,y0-hgt*.25);b.lineTo(x0+w*.55,y0-hgt*.5);b.stroke();
  if(Math.floor(T*3+e.x)%4===0){b.fillStyle='#ffffff';b.fillRect(x0-w*.5|0,(y0-hgt*.8)|0,2,2)}b.restore()}
function drawEnt(e,L){if(e.indoor)return;const fr=entFrame(e,e.spinT>0?Math.floor(T*30)%8:(e.d8||0),e.anim||'idle',e.frame||0);const [wx,wy]=wpx(e.x,e.y);const gx=Math.round(wx-sx0)+(e.flinch>0?Math.round(Math.sin(e.flinch*95)*2.2):0),gy=Math.round(wy-sy0),by=gy-Math.round(e.z||0);
  const sc=(e.look.scale||1)*(e.look.beast?1.35:1);const sw=Math.round(22*sc);b.globalAlpha=e.dying?Math.max(0,e.dying/.7):1;b.drawImage(LS.shadow,gx-sw*.65,gy-sw*.25,Math.round(sw*1.3),Math.round(sw*.5));b.drawImage(LS.shadow,gx-sw/2,gy-sw*.19,sw,Math.round(sw*.38));
  if(e.type==='remote'&&e.dead)b.globalAlpha=.35;if(e.type==='remote'&&e.st)b.globalAlpha*=.3;
  if(e===P&&P.dead){b.save();b.translate(gx,gy-4);b.rotate(-Math.PI/2);b.globalAlpha=.85;b.drawImage(fr.cv,-fr.ay,-fr.ax);b.restore();b.globalAlpha=1;return}
  if(e.sleep||(e.def&&e.def.ai==='scarecrow'&&e.z>0)){b.fillStyle='#4a3422';b.fillRect(gx-1,by-Math.round(fr.ay*.5),3,Math.round(fr.ay*.5)+(gy-by)+1);b.fillStyle='#5a4028';b.fillRect(gx-13,by-Math.round(fr.ay*.62),26,2);b.fillStyle='#2a1c12';b.fillRect(gx-13,by-Math.round(fr.ay*.62)+2,26,1)}
  if(e.def&&e.def.ai==='scarecrow'&&!e.sleep&&!e.dying){L.push([gx,by-Math.round(fr.ay*.8),34,1])}
  let img=fr.cv;if(e.flash>0)img=whiteOf(img);else if(e.slowT>0)img=tintOf(img,'#9ad8ff',.4);else if(e.buff&&e.buff.war>0&&Math.floor(T*6)%2)img=tintOf(img,'#ffb040',.25);
  if(e.look.ghost){b.globalAlpha*=.7+.15*Math.sin(T*4);img=tintOf(fr.cv,'#7adfff',.35)}if(e.clone){b.globalAlpha*=.55+.1*Math.sin(T*8);img=tintOf(fr.cv,'#8a3ae8',.6)}if(e===P&&P.ifr>0&&!P.dash)b.globalAlpha*=.6;if(e===P&&P.stealth>0)b.globalAlpha*=.32;
  if(e.frozenT>0)img=tintOf(fr.cv,'#a8e4ff',.55);b.drawImage(img,gx-fr.ax,by-fr.ay);if(e.frozenT>0)drawIceBlock(gx,gy,fr,e);b.globalAlpha=1;e._bb=[gx-fr.ax,by-fr.ay,fr.cv.width,fr.cv.height];
  if(e.stunT>0)for(let i=0;i<3;i++){const a=T*5+i*2.1;b.fillStyle='#ffe066';b.fillRect(Math.round(gx+Math.cos(a)*7),Math.round(by-fr.ay+4+Math.sin(a)*2),2,2)}
  if(e.rootT>0){b.strokeStyle='#8a7a4a';b.beginPath();b.ellipse(gx,gy,10,4,0,0,7);b.stroke()}
  if(e.look.ghost)L.push([gx,by-20,70,2]);if((e.champ||(e.def&&e.def.elite))&&!e.dying){L.push([gx,gy-8,60,1]);if(Math.random()<.2){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-10,10),y:wy-rnd(0,8),vx:0,vy:rnd(-30,-14),g:0,t:0,life:.7,col:'#ffd23a',glow:1})}}if(e.look.fire&&!e.dying){L.push([gx,gy-10,110,1]);if(Math.random()<.5){const [wx,wy]=wpx(e.x+rnd(-.6,.6),e.y+rnd(-.6,.6));fx.push({type:'px',x:wx,y:wy-rnd(4,14),vx:rnd(-6,6),vy:rnd(-40,-16),g:0,t:0,life:rnd(.4,.9),col:pick(['#ffb04a','#ff6a1a','#fff0a0']),glow:1})}}if(e.poison&&e.bleedT>0&&!e.dying&&Math.random()<.3){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-7,7),y:wy-rnd(6,24),vx:0,vy:rnd(-22,-10),g:0,t:0,life:rnd(.4,.8),col:pick(['#9ae85a','#d8ff8a','#3a8a2a'])})}
  if(e.burn&&e.bleedT>0&&!e.dying){const ob=e._bb;drawFlame(gx-4,gy-4,3,e.x*7,'fire');drawFlame(gx+4,gy-10,2,e.y*5,'fire');drawFlame(gx,by-Math.round((fr.ay||20)*.55),2,e.x*3+1,'fire');L.push([gx,gy-12,60,1])}
  if(e.look.frostBlade&&!e.dying){L.push([gx,by-26,56,2]);if(Math.random()<.25){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-10,10),y:wy-rnd(16,34),vx:rnd(-4,4),vy:rnd(4,16),g:20,t:0,life:rnd(.4,.9),col:pick(['#ffffff','#bfe8ff','#7ac8f0'])})}}
  if(e.buff&&e.buff.war>0&&!e.dying){L.push([gx,gy-14,70,1]);if(Math.random()<.5){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-9,9),y:wy-rnd(0,8),vx:rnd(-3,3),vy:rnd(-45,-25),g:0,t:0,life:rnd(.4,.8),col:pick(['#ffcc5a','#ff6a3a','#ffe8a0']),glow:1})}}
  if(e.look.fireBlade&&!e.dying){L.push([gx,by-26,64,1]);if(Math.random()<.3){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-10,10),y:wy-rnd(18,34),vx:rnd(-6,6),vy:rnd(-32,-12),g:0,t:0,life:rnd(.4,.9),col:pick(['#ffb04a','#ff6a1a','#fff0a0'])})}}if(e.look.holy&&Math.random()<.12){const [wx,wy]=wpx(e.x,e.y);fx.push({type:'px',x:wx+rnd(-8,8),y:wy-rnd(12,28),vx:0,vy:-10,g:0,t:0,life:.8,col:'#fff0a0'})}if(e.def&&e.def.boss&&!e.dying)L.push([gx,by-30,80,1])}
function drawLoot(l,L){const [x,y]=iso(l.x,l.y);const bob=Math.round(Math.sin(T*3+l.x*3)*1.5)-(l.age<.35?Math.round(Math.sin(l.age/.35*Math.PI)*10):0);b.drawImage(LS.shadow,x-7,y-3,14,5);
  if(l.tomb){b.fillStyle='#8a8894';b.fillRect(x-1,y-14+bob*0,3,14);b.fillRect(x-5,y-10,11,3);b.fillStyle='#ffd860';b.fillRect(x-3,y-2,6,2);l._bb=[x-6,y-16,12,16];L.push([x,y-8,40,1]);return}
  if(l.gold){for(const [dx,dy] of [[-3,0],[2,-1],[0,-3]]){b.fillStyle='#a8782a';b.fillRect(x+dx-2,y+dy-3+bob,5,3);b.fillStyle='#ffd860';b.fillRect(x+dx-2,y+dy-4+bob,5,2)}l._bb=[x-6,y-8,12,10];return}
  const r=l.item.r||0;if(r>=1){b.globalCompositeOperation='lighter';b.fillStyle=RAR[r].c+'55';b.fillRect(x-2,y-40,4,38);b.fillStyle=RAR[r].c+'22';b.fillRect(x-5,y-30,10,28);b.globalCompositeOperation='source-over';L.push([x,y-10,40,r>=3?1:2])}
  b.drawImage(iconCanvas(l.item.id),x-10,y-20+bob);l._bb=[x-10,y-20,20,20]}
function drawProj(p,L){const [x,y]=iso(p.x,p.y);const h=12;const sa=Math.atan2((Math.cos(p.a)+Math.sin(p.a))*16,(Math.cos(p.a)-Math.sin(p.a))*32);const dx=Math.cos(sa),dy=Math.sin(sa);if(drawProjX(p,x,y,h,dx,dy,L))return;
  if(p.kind==='ice'){b.strokeStyle='#7ac8f0';b.lineWidth=4;b.beginPath();b.moveTo(x-dx*9,y-h-dy*9);b.lineTo(x+dx*6,y-h+dy*6);b.stroke();b.strokeStyle='#ffffff';b.lineWidth=2;b.beginPath();b.moveTo(x-dx*5,y-h-dy*5);b.lineTo(x+dx*7,y-h+dy*7);b.stroke();b.lineWidth=1;return}
  if(p.kind==='quarrel'){b.strokeStyle='#c8ccd8';b.lineWidth=2;b.beginPath();b.moveTo(x-dx*6,y-h-dy*6);b.lineTo(x+dx*5,y-h+dy*5);b.stroke();b.lineWidth=1;b.fillStyle='#ffffff';b.fillRect(Math.round(x+dx*5)-1,Math.round(y-h+dy*5)-1,2,2);return}
  if((p.kind==='arrow'||p.kind==='quarrel')&&p.o&&p.o.el){const c=({fire:'#ffb04a',frost:'#cfeeff',poison:'#9ae85a',nature:'#8af05a',song:'#ffe08a',void:'#c08aff',rage:'#ff5a3a'})[p.o.el]||'#fff';b.fillStyle=c;b.globalAlpha=.5;b.fillRect(Math.round(x+dx*5)-2,Math.round(y-h+dy*5)-2,4,4);b.globalAlpha=1}
  if(p.kind==='arrow'||p.kind==='garrow'){b.strokeStyle=p.kind==='arrow'?'#e8dcc0':'#5a3a22';b.lineWidth=1;b.beginPath();b.moveTo(x-dx*7,y-h-dy*7);b.lineTo(x+dx*5,y-h+dy*5);b.stroke();b.fillStyle=p.kind==='arrow'?'#d8dee8':'#8a8a96';b.fillRect(Math.round(x+dx*5)-1,Math.round(y-h+dy*5)-1,2,2);b.fillStyle=p.kind==='arrow'?'#e84a3a':'#3a5a2a';b.fillRect(Math.round(x-dx*7)-1,Math.round(y-h-dy*7)-1,2,2);b.fillStyle='rgba(0,0,0,.25)';b.fillRect(Math.round(x)-2,Math.round(y),4,1)}
  else{const c=p.kind==='holy'?['#ffffff','#ffd86a']:p.kind==='fire'?['#fff0a0','#ff8a2a']:p.kind==='arcane'?['#e0ffff','#4ad0e8']:['#ffffff','#8ab0ff'];const r=p.kind==='fire'?4:3;b.fillStyle=c[1];b.beginPath();b.arc(x,y-h,r,0,7);b.fill();b.fillStyle=c[0];b.beginPath();b.arc(x-1,y-h-1,r*.5,0,7);b.fill();b.fillStyle='rgba(0,0,0,.25)';b.fillRect(Math.round(x)-2,Math.round(y),4,1)}}
function drawFx(f,glowPass){const glow=!!f.glow||f.type==='spark'||f.type==='ring'||f.type==='meteor'||f.type==='slash'||f.type==='beam'||f.type==='zap'||f.type==='arc'||f.type==='whirl'||f.type==='roar';if(glow!==glowPass)return;const k=f.t/f.life;
  switch(f.type){
    case'whirl':{const [x,y]=iso(f.x,f.y);const C={fire:['#fff0a0','#ff8a2a'],frost:['#ffffff','#9ad8ff'],storm:['#ffffff','#7ab8ff'],rage:['#ffd0b0','#ff3a1a'],void:['#f4e0ff','#a46aff'],nature:['#eaffb8','#6ae04a']}[f.el]||['#ffffff','#e8d8b0'];const R=f.r*44;b.save();b.translate(x,y-10);b.scale(1,.5);const head=k*Math.PI*4;for(let i=0;i<9;i++){const a0=head-i*.28;b.globalAlpha=(1-i/9)*(1-k*.5);b.strokeStyle=i<2?C[0]:C[1];b.lineWidth=Math.max(1,6-i*.6);b.beginPath();b.arc(0,0,R*(1-i*.025),a0-.3,a0);b.stroke()}b.globalAlpha=.25*(1-k);b.fillStyle=C[1];b.beginPath();b.arc(0,0,R,0,7);b.fill();b.restore();b.globalAlpha=1;break}
    case'roar':{const [x,y]=iso(f.x,f.y);for(let i=0;i<3;i++){const kk=Math.min(1,k*1.4+i*.15);b.globalAlpha=(1-kk)*.8;b.strokeStyle=i%2?'#ff6a3a':'#ffd86a';b.lineWidth=2;b.beginPath();b.arc(x,y-26,6+kk*40,-Math.PI*.85,-Math.PI*.15);b.stroke()}b.globalAlpha=1;break}
    case'crack':{const fade=k<.75?1:1-(k-.75)/.25,grow=Math.min(1,f.t/.12);const glowC={fire:'#ff8a2a',frost:'#9ae8ff',storm:'#9ad8ff',rage:'#ff3a1a',void:'#a46aff',nature:'#6ae04a'}[f.el];for(const sg of f.segs){const n=Math.max(2,Math.round(sg.length*grow));b.globalAlpha=fade;b.strokeStyle='#1a120c';b.lineWidth=4;b.beginPath();for(let i=0;i<n;i++){const [x,y]=iso(sg[i][0],sg[i][1]);i?b.lineTo(x,y):b.moveTo(x,y)}b.stroke();b.strokeStyle=glowC||'#6a5a44';b.lineWidth=glowC?2:1;b.globalAlpha=fade*(glowC?.9*(1-k*.6):.8);b.stroke()}b.globalAlpha=1;break}
    case'zap':{const [x,y]=iso(f.x,f.y);let r=f.seed+Math.floor(f.t*30);const rr=()=>{r=(r*9301+49297)%233280;return r/233280};const pts=[];let cx=x+(rr()-.5)*30,cy=y-150;for(let i=0;i<=9;i++){const t=i/9;pts.push([lerp(cx,x,t)+(i&&i<9?(rr()-.5)*16:0),lerp(cy,y-2,t)])}b.globalAlpha=1-k*.7;b.strokeStyle='#7ab8ff';b.lineWidth=4;b.beginPath();pts.forEach((q,i)=>i?b.lineTo(q[0],q[1]):b.moveTo(q[0],q[1]));b.stroke();b.strokeStyle='#ffffff';b.lineWidth=1.5;b.stroke();if(k<.4){b.fillStyle='rgba(220,240,255,.8)';b.beginPath();b.ellipse(x,y,14*(1-k),7*(1-k),0,0,7);b.fill()}b.globalAlpha=1;break}
    case'arc':{const [x1,y1]=iso(f.x,f.y),[x2,y2]=iso(f.x2,f.y2);let r=Math.floor(f.t*40)+7;const rr=()=>{r=(r*9301+49297)%233280;return r/233280};b.globalAlpha=1-k*.6;b.strokeStyle='#bfe8ff';b.lineWidth=2;b.beginPath();b.moveTo(x1,y1-14);for(let i=1;i<6;i++){const t=i/6;b.lineTo(lerp(x1,x2,t)+(rr()-.5)*12,lerp(y1,y2,t)-14+(rr()-.5)*10)}b.lineTo(x2,y2-14);b.stroke();b.globalAlpha=1;break}
    case'px':{b.globalAlpha=1-k*.6;b.fillStyle=f.col;const z=f.sz||(f.glow?1:2);b.fillRect(Math.round(f.x-sx0),Math.round(f.y-sy0),z,z);b.globalAlpha=1;break}
    case'p':{const [x,y]=iso(f.x,f.y);b.globalAlpha=1-k;b.fillStyle=f.col;b.fillRect(Math.round(x),Math.round(y-(f.up||8)-k*10),2,2);b.globalAlpha=1;break}
    case'spark':{const x=Math.round(f.x-sx0),y=Math.round(f.y-sy0);b.globalAlpha=Math.sin(k*Math.PI)*.8;b.fillStyle='#e8f8ff';b.fillRect(x-1,y,3,1);b.fillRect(x,y-1,1,3);b.globalAlpha=1;break}
    case'smoke':{const x=f.x-sx0+f.vx*f.t,y=f.y-sy0-f.t*(f.sm?6:16);b.globalAlpha=(1-k)*(f.sm?.45:.35);b.fillStyle=f.col||'#c8c4cc';b.beginPath();b.arc(x,y,3+k*6,0,7);b.fill();b.globalAlpha=1;break}
    case'ghost':b.globalAlpha=(1-k)*.35;b.drawImage(tintOf(f.cv,f.col||'#bfe0ff',.6),Math.round(f.x-sx0),Math.round(f.y-sy0));b.globalAlpha=1;break;
    case'slash':{const [x,y]=iso(f.x,f.y);const sa=Math.atan2((Math.cos(f.a)+Math.sin(f.a))*16,(Math.cos(f.a)-Math.sin(f.a))*32);b.save();b.translate(x,y-12);b.scale(1,.55);b.globalAlpha=(1-k)*(f.dim?.4:.9);b.strokeStyle=f.col||(f.heavy?'#ffd08a':'#ffffff');b.lineWidth=f.heavy?4:2;const R=f.r*40*(.8+k*.3);b.beginPath();b.arc(0,0,R,sa-f.arc/2+k*.4,sa+f.arc/2+k*.4);b.stroke();b.globalAlpha*=.5;b.lineWidth=1;b.beginPath();b.arc(0,0,R*.8,sa-f.arc/2+k*.3,sa+f.arc/2+k*.3);b.stroke();b.restore();b.globalAlpha=1;break}
    case'ring':{const [x,y]=iso(f.x,f.y);b.globalAlpha=1-k;b.strokeStyle=f.col;b.lineWidth=f.ice?2:2;b.beginPath();b.ellipse(x,y,Math.max(1,f.r*45*(.3+k*.7)),Math.max(1,f.r*22.6*(.3+k*.7)),0,0,7);b.stroke();b.globalAlpha=1;break}
    case'beam':{const [x1,y1]=iso(f.x,f.y),[x2,y2]=iso(f.x2,f.y2);b.globalAlpha=1-k;b.strokeStyle=f.col;b.lineWidth=2;b.beginPath();b.moveTo(x1,y1-16);b.lineTo(x2,y2-14);b.stroke();b.globalAlpha=1;break}
    case'arrowfall':{const [x,y]=iso(f.x,f.y);const yy=y-40*(1-k);b.strokeStyle='#e8dcc0';b.beginPath();b.moveTo(x,yy-6);b.lineTo(x,yy);b.stroke();if(k>.9)burstAt(f.x,f.y,0xc8b090,1,20);break}
    case'hitfx':drawHitFx(f,k);break;
    case'note':{b.globalAlpha=1-k;b.fillStyle=f.col;const x=Math.round(f.x-sx0),y=Math.round(f.y-sy0);b.fillRect(x,y,3,2);b.fillRect(x+2,y-5,1,6);b.fillRect(x+2,y-5,3,1);b.globalAlpha=1;f.x+=f.vx*.016;f.y+=f.vy*.016;break}
    case'meteor':{const [x,y]=iso(f.x,f.y);const yy=y-260*(1-k),xx=x-120*(1-k);b.fillStyle='#ff8a2a';b.beginPath();b.arc(xx,yy,6,0,7);b.fill();b.fillStyle='#fff0a0';b.beginPath();b.arc(xx,yy,3,0,7);b.fill();for(let i=1;i<6;i++){b.globalAlpha=.5-i*.08;b.fillStyle='#ff6a1a';b.beginPath();b.arc(xx-i*6,yy-i*12,6-i,0,7);b.fill()}b.globalAlpha=1;break}}}
const snow=[];function drawSnow(dt,k){const n=Math.round(k*160);while(snow.length<n)snow.push({x:rnd(0,BW),y:rnd(-BH,BH),s:rnd(18,42),ph:rnd(0,6.28),z:Math.random()});snow.length=Math.min(snow.length,n);for(const f of snow){f.y+=f.s*dt*(.6+f.z);f.x+=Math.sin(T*1.3+f.ph)*12*dt-8*dt;if(f.y>BH){f.y=rnd(-20,0);f.x=rnd(0,BW)}if(f.x<-4)f.x=BW+2;b.fillStyle=f.z>.6?'rgba(255,255,255,.95)':'rgba(220,232,248,.7)';const z=f.z>.75?2:1;b.fillRect(Math.round(f.x),Math.round(f.y),z,z)}}
const rain=[];function drawRain(dt){const n=Math.round(rainNow()*140);while(rain.length<n)rain.push({x:rnd(0,BW+60),y:rnd(-BH,BH),s:rnd(300,420)});rain.length=Math.min(rain.length,n);b.strokeStyle='rgba(190,210,240,.45)';b.lineWidth=1;b.beginPath();for(const r of rain){r.y+=r.s*dt;r.x-=r.s*.25*dt;if(r.y>BH){r.y=rnd(-40,0);r.x=rnd(0,BW+60);if(Math.random()<.4)fx.push({type:'px',x:r.x+sx0,y:rnd(0,BH)+sy0,vx:rnd(-10,10),vy:-20,g:120,t:0,life:.2,col:'#c8d8f0'})}b.moveTo(r.x,r.y);b.lineTo(r.x+2,r.y-7)}b.stroke()}
const flies=[];function tickFx(dt){if(P&&state==='play'&&!M.indoor&&M.climate){const cl=M.climate,k=M.id==='japao'?.55:cl==='desert'?.45:cl==='jungle'?.35:0;if(Math.random()<k){const x=sx0+rnd(-40,BW+40),y=sy0+rnd(-40,BH);if(M.id==='japao')fx.push({type:'px',x,y,vx:rnd(8,22),vy:rnd(6,14),g:0,t:0,life:rnd(3,6),col:pick(['#f6c0d0','#f0a0bc','#ffe0ea']),sz:2,petal:1});else if(cl==='desert')fx.push({type:'px',x,y,vx:rnd(10,26),vy:rnd(-3,3),g:0,t:0,life:rnd(2,4),col:pick(['#f0d8a0','#e8c888','#fff0c8']),glow:1});else fx.push({type:'px',x,y,vx:rnd(-4,4),vy:rnd(-6,-1),g:0,t:0,life:rnd(2.5,5),col:pick(['#e8f0a0','#c8e878','#fff8c0']),glow:1})}}
  if(P&&state==='play'){const want=M.id==='santuario'?18:(!M.indoor&&nightF()>.35&&weather.rain<.5)?10:0;if(flies.length<want&&Math.random()<(M.id==='santuario'?.05:.012)){const a=Math.random()*6.28,r=rnd(3,10),x=P.x+Math.cos(a)*r,y=P.y+Math.sin(a)*r,t=tAt(M,x,y);if(t===GRASS||t===FOREST||t===GRAVE||t===12||t===FIELD||t===JUNGLE||t===JGRASS||t===MUD)flies.push({x,y,z:rnd(8,30),vx:0,vy:0,ph:Math.random()*6,sp:rnd(1.5,3.5),life:rnd(8,16),t:0})}}
  for(let i=flies.length-1;i>=0;i--){const f=flies[i];f.t+=dt;f.ph+=dt*f.sp;f.vx+=rnd(-1,1)*dt;f.vy+=rnd(-1,1)*dt;f.vx*=.98;f.vy*=.98;f.x+=f.vx*dt*.6;f.y+=f.vy*dt*.6;f.z+=Math.sin(f.t*1.3)*dt*4;if(f.t>f.life||(P&&Math.hypot(f.x-P.x,f.y-P.y)>14)||M.indoor&&M.id!=='santuario')flies.splice(i,1)}
for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.t+=dt;if(f.type==='px'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=f.g*dt}else if(f.type==='p'){f.x+=f.vx*dt;f.y+=f.vy*dt}if(f.t>=f.life)fx.splice(i,1)}if(fx.length>900)fx.splice(0,fx.length-900);
  for(let i=texts.length-1;i>=0;i--){texts[i].t+=dt;if(texts[i].t>=texts[i].life)texts.splice(i,1)}
  if(P&&state==='play'&&Math.random()<(M.indoor?.25:.08)){const [wx,wy]=wpx(P.x+rnd(-8,8),P.y+rnd(-8,8));fx.push({type:'px',x:wx,y:wy-rnd(0,40),vx:rnd(-4,4),vy:rnd(-14,-4),g:0,t:0,life:rnd(2,4),col:M.indoor?'#ff6a4a':'#c8b8a0',glow:M.indoor?1:0})}
  if(P&&state==='play'&&nightF()>.5&&!M.indoor&&Math.random()<.1){const a=Math.random()*6.28,r=rnd(2,7);const t=tAt(M,P.x+Math.cos(a)*r,P.y+Math.sin(a)*r);if(t===GRASS||t===FOREST){const [wx,wy]=wpx(P.x+Math.cos(a)*r,P.y+Math.sin(a)*r);fx.push({type:'px',x:wx,y:wy-rnd(8,24),vx:rnd(-6,6),vy:rnd(-6,2),g:0,t:0,life:rnd(1.5,3),col:'#d8ff8a',glow:1})}}}
function overlay(){const fs=Math.max(12*DPR,Math.round(5.6*K)),toD=(wx,wy)=>[(wx-sx0)*K,(wy-sy0)*K];vx.textAlign='center';vx.textBaseline='top';vx.lineJoin='round';
  const label=(e,txt,col,dy=7)=>{const [wx,wy]=wpx(e.x,e.y),[dx,dyy]=toD(wx,wy+dy);vx.font=`${fs}px VT323, monospace`;vx.lineWidth=Math.max(2,fs/5);vx.strokeStyle='#000';vx.strokeText(txt,dx,dyy);vx.fillStyle=col;vx.fillText(txt,dx,dyy)};
  if(state==='play'){if(!P.dead)label(P,P.name+(P.title?` «${P.title}»`:''),'#ffffff',11);
    if(M.id==='world')for(const bt of bots)label(bt,bt.name,'#a8ccff',8);
    for(const g of remoteMobs())if(g.m===M.id&&!g.dying)label(g,`${g.def.n} · luta de ${g.owner}`,'#9ae8c8',g.def.boss?20:12);
    for(const r of remotes.values())if(r.m===M.id&&!r.st)label(r,(party&&r.pt===party?'★ ':'')+`${r.name}${r.ti?` «${r.ti}»`:''} · Nv${r.lv}`,party&&r.pt===party?'#ffd86a':'#7af0b0',11);
    for(const n of npcs)if(n.m===M.id&&!n.hidden&&!n.indoor&&dist(n,P)<12)label(n,n.n.split(',')[0],'#f2cf7a',8);
    for(const m of mobs){if(m.m!==M.id||m.dying||m.dead)continue;if(m.def.ai==='dummy'){const recent=m.dps.filter(e=>T-e[0]<4);if(recent.length){const sum=recent.reduce((s,e)=>s+e[1],0),span=Math.max(1,T-recent[0][0]);label(m,`DPS ${Math.round(sum/span)}`,'#ffe08a',-62)}continue}
      if(!m.sleep&&(m===hoverMob||m.hpShow>0||m.def.boss||m.def.elite||m.champ)){const df=m.lv-P.lv,col=m.champ?'#ffd23a':m.def.elite?'#ffb050':df<=-3?'#9a9a9a':df<=1?'#ffffff':df<=3?'#ffb050':'#ff5a4a';if(!m.def.boss)label(m,`${m.champ?'★ Campeão ':m.def.elite?'★ ':''}${m.def.n} Nv${m.lv}`,col,m.def.elite||m.champ?16:12)}}}
  const ents=[P,...npcs,...bots,...mobs,...remotes.values()];for(const e of ents){if(!e||!e.bub)continue;if(e.m&&e.m!==M.id)continue;if(e.type==='bot'&&M.id!=='world')continue;const [wx,wy]=wpx(e.x,e.y);const top=e.look&&e.look.scale>1.2?80:e.type==='mob'?48:66;let [dx,dy]=toD(wx,wy-top);vx.font=`${fs}px VT323, monospace`;const tw=vx.measureText(e.bub.txt).width,pad=fs*.4,bw=tw+pad*2,bh=fs*1.15;
    vx.fillStyle='rgba(246,240,226,.94)';vx.strokeStyle='#1a1418';vx.lineWidth=Math.max(1,DPR);vx.fillRect(dx-bw/2,dy-bh,bw,bh);vx.strokeRect(dx-bw/2,dy-bh,bw,bh);vx.fillStyle='#1a1418';vx.fillText(e.bub.txt,dx,dy-bh+fs*.1)}
  for(const t of texts){if(/^\d+$/.test(t.txt)){drawDmgNum(t,fs,toD);continue}const k=t.t/t.life,[dx,dy]=toD(t.wx+t.vx*t.t,t.wy-40*t.t+40*t.t*t.t);const sz=Math.round(fs*(t.big?1.5:1.2)*(t.t<.08?1.3:1));vx.font=`700 ${sz}px "Pixelify Sans", monospace`;vx.globalAlpha=k>.7?(1-k)/.3:1;vx.lineWidth=Math.max(3,sz/4);vx.strokeStyle='#000';vx.strokeText(t.txt,dx,dy);vx.fillStyle=t.col;vx.fillText(t.txt,dx,dy);vx.globalAlpha=1}
  if(lvlFx>0&&P){const [wx,wy]=wpx(P.x,P.y),[dx,dy]=toD(wx,wy-70-(1.8-lvlFx)*14);const sz=Math.round(fs*1.6);vx.font=`700 ${sz}px "Pixelify Sans", monospace`;vx.globalAlpha=Math.min(1,lvlFx);vx.lineWidth=sz/4;vx.strokeStyle='#000';vx.strokeText('NÍVEL '+P.lv+'!',dx,dy);vx.fillStyle='#ffd23a';vx.fillText('NÍVEL '+P.lv+'!',dx,dy);vx.globalAlpha=1}}

const VIG={c:null,w:0,h:0};function buildVig(){const [c,x]=mk(BW,BH);const g=x.createRadialGradient(BW/2,BH/2,Math.min(BW,BH)*.32,BW/2,BH/2,Math.max(BW,BH)*.72);g.addColorStop(0,'rgba(4,6,14,0)');g.addColorStop(1,'rgba(4,6,14,.62)');x.fillStyle=g;x.fillRect(0,0,BW,BH);VIG.c=c;VIG.w=BW;VIG.h=BH}
function grade(nf){const dung=M.indoor,s=sunLevel(),dusk=dung?0:clamp(1-Math.abs(s-.36)/.18,0,1);
  b.globalCompositeOperation='saturation';b.fillStyle=`rgba(128,128,128,${dung?.22:.28+nf*.18+rainNow()*.12})`;b.fillRect(0,0,BW,BH);
  let tint=dung?(M.tint||0x8a8cb4):mix(mix(0xc4cee0,0xe0a88e,dusk),0x7a8ab4,nf*.85);if(!dung&&rainNow()>.02)tint=mix(tint,0x8a96aa,rainNow()*.6);if(!dung&&M.gradeTint)tint=mix(tint,M.gradeTint,.3*(1-nf*.5));
  b.globalCompositeOperation='multiply';b.fillStyle=hex(tint);b.fillRect(0,0,BW,BH);
  b.globalCompositeOperation='soft-light';b.fillStyle=dung?(M.soft||'rgba(40,90,100,.25)'):`rgba(30,60,90,${.18+nf*.1})`;b.fillRect(0,0,BW,BH);if(!dung&&M.oSoft){b.fillStyle=M.oSoft;b.fillRect(0,0,BW,BH)}
  b.globalCompositeOperation='source-over'}

// ---------- pixel-art finish: curated palette + ordered dithering ----------
const PALETTE=[0x0e121e,0x141c2a,0x1c2434,0x262e40,0x2e3626,0x202a22,0x3a3446,0x2a2432,0x4a4038,0x34302e,0x0b0c14,0x161a26,0x232838,0x323a4c,0x465064,0x5e687c,0x7a8496,0x9aa2b2,0xbcc2cc,0xdfe2e6,0xffffff,
  0x1a2a2e,0x263c40,0x34504f,0x46665f,0x5e7e74,0x7e9a8c,0x14201a,0x1e3024,0x2a4230,0x38563a,0x4a6a42,0x5e7e4a,0x7a9456,0x9aac66,0x6e6e3e,0x8e8a4e,0xaea860,
  0x1e1612,0x2e2018,0x42301f,0x5a4028,0x745434,0x926c44,0xb08a5a,0xceaa7a,0x8a5e46,0xb07c5a,0xd4a07a,0xecc8a0,0xf8e6c8,
  0x2e0e14,0x4e1a1e,0x742a28,0x9e3a30,0xc8503a,0xe8744a,0xf09a4a,0xf8c060,0xffe08a,0xfff4c8,
  0x10182e,0x1a2a4a,0x263e66,0x34568a,0x4a74aa,0x6a96c8,0x9abce0,0x1e1428,0x2e1e3c,0x443054,0x5e4670,0x7c6290,0x9e86b0,0x6a3a52,0x9a5470,0x3a4a3e,0x52604e,0x6e5a50,0x8c7868];
let LUT=null;const BAYER=[0,8,2,10,12,4,14,6,3,11,1,9,15,7,13,5].map(v=>(v/16-.47)*8);
function buildLUT(){LUT=new Uint32Array(32768);const pr=PALETTE.map(c=>[c>>16&255,c>>8&255,c&255]);for(let r=0;r<32;r++)for(let g=0;g<32;g++)for(let bb=0;bb<32;bb++){const R=r*8+4,G=g*8+4,B=bb*8+4;let best=0,bd=1e12;for(let i=0;i<pr.length;i++){const dr=R-pr[i][0],dg=G-pr[i][1],db=B-pr[i][2],rm=(R+pr[i][0])/2;const d=(2+rm/256)*dr*dr+4*dg*dg+(2+(255-rm)/256)*db*db;if(d<bd){bd=d;best=i}}const c=pr[best];LUT[(r<<10)|(g<<5)|bb]=0xff000000|(c[2]<<16)|(c[1]<<8)|c[0]}}
function pixelFinish(){if(!LUT)buildLUT();const half=CFG.pixelFinish===1,id=b.getImageData(0,0,BW,BH),d=new Uint32Array(id.data.buffer),W=BW;for(let y=0;y<BH;y++){const row=y*W,by=(y&3)<<2;for(let x=0;x<W;x++){const i=row+x,v=d[i],t=half?BAYER[by|(x&3)]*.3:BAYER[by|(x&3)];let r=(v&255)+t,g=((v>>8)&255)+t,bl=((v>>16)&255)+t;r=r<0?0:r>255?255:r;g=g<0?0:g>255?255:g;bl=bl<0?0:bl>255?255:bl;const q=LUT[((r>>3)<<10)|((g>>3)<<5)|(bl>>3)];if(half){d[i]=0xff000000|((((v>>16)&255)+((q>>16)&255)*2)/3<<16)|((((v>>8)&255)+((q>>8)&255)*2)/3<<8)|(((v&255)+(q&255)*2)/3)}else d[i]=q}}b.putImageData(id,0,0)}
