// ===================== interface =====================
let uiDirty=1,shopKey=null,bankOpen=false,hudT=0;
const showWin=s=>{$(s).hidden=false},hideWin=s=>{$(s).hidden=true;if(s==='#shopWin')shopKey=null;if(s==='#bankWin')bankOpen=false};
function toggleWin(s,fn){const w=$(s);if(w.hidden){w.hidden=false;fn&&fn()}else hideWin(s)}
document.querySelectorAll('[data-close]').forEach(bt=>bt.addEventListener('click',()=>hideWin('#'+bt.closest('.win').id)));
function log(txt,cls='bot',col){const l=$('#log'),p=document.createElement('p');p.className=cls;p.textContent=txt;if(col)p.style.color=col;l.appendChild(p);while(l.children.length>90)l.firstChild.remove();l.scrollTop=l.scrollHeight}
let toastT;function toast(a,b2){const t=$('#toast');t.querySelector('.a').textContent=a;t.querySelector('.b').textContent=b2||'';t.classList.add('on');clearTimeout(toastT);toastT=setTimeout(()=>t.classList.remove('on'),2200)}
let bannerT;function regionBanner(r){const bn=$('#banner');$('#bnN').textContent=r.n;const l=$('#bnL');l.textContent=r.lv;l.dataset.dg=r.dg;bn.classList.add('on');clearTimeout(bannerT);bannerT=setTimeout(()=>bn.classList.remove('on'),2800);$('#regName').textContent=r.n;const rl=$('#regLv');rl.textContent=r.lv;rl.dataset.dg=r.dg}
function dlg(name,text,opts){$('#dlgName').textContent=name;$('#dlgText').textContent=text;const a=$('#dlgActs');a.innerHTML='';if(!opts.length)opts=[{l:'Fechar'}];for(const o of opts){const e=document.createElement('button');e.type='button';e.className='btn'+(o.pri?' pri':'');e.textContent=o.l;e.onclick=()=>{hideWin('#dlg');o.f&&o.f()};a.appendChild(e)}showWin('#dlg')}
// ---------- tooltip ----------
const tip=$('#tooltip');
function compareHTML(it,esc){const b=BASES[it.id];if(!P||b.t!=='eq'||P.eq[b.slot]===it||(b.cls&&b.cls!==P.cls))return'';const cur=P.eq[b.slot];const eq2=Object.assign({},P.eq,{[b.slot]:it});if(b.two)delete eq2.escudo;if(b.slot==='escudo'&&P.eq.arma&&BASES[P.eq.arma.id].two)delete eq2.arma;
  let a,c;try{a=D(P);c=D(Object.assign({},P,{eq:eq2}))}catch(e){return''}const ws=e=>e.arma?(BASES[e.arma.id].as||1):1;
  const rows=[['Ataque',a.atk,c.atk,0],['Dano por segundo',a.atk*a.aspd*ws(P.eq),c.atk*c.aspd*ws(eq2),1],['Defesa',a.def,c.def,0],['Vida',a.maxHp,c.maxHp,0],['Mana',a.maxMp,c.maxMp,0],['Crítico',a.crit,c.crit,1],['Velocidade',a.speed,c.speed,2]];
  const out=[];for(const [n,x,y,dec] of rows){const d=y-x;if(Math.abs(d)<(dec?.05:.5))continue;const f=dec===2?Math.round(d/x*100)+'%':dec?d.toFixed(1):Math.round(d);out.push(`<span class="${d>0?'up':'down'}">${d>0?'▲ +':'▼ '}${f} ${n}</span>`)}
  return `<div class="cmp"><span class="mut">Comparado com ${cur?esc(BASES[cur.id].n):'o espaço vazio'}:</span><br>${out.length?out.join('<br>'):'<span class="mut">Sem diferença nos atributos</span>'}</div>`}
function itemTipHTML(it,extra){const b=BASES[it.id],r=it.r||0,rr=RAR[r];const lines=[];const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'})[c]);
  lines.push(`<b style="color:${b.t==='eq'?rr.c:'#ece4d4'}">${esc(b.n)}${it.up?' +'+it.up:''}${it.n>1?' ×'+it.n:''}</b>`);
  if(b.t==='eq'){const sl=SLOTS.find(s=>s[0]===b.slot)[1];lines.push(`<span class="mut">${rr.n} · ${sl}${b.cls?' · '+CLASSES[b.cls].n:''}${it.up?` · refino +${it.up} (+${it.up*7}%)`:''}</span>`);const m=rr.m*(1+(it.up||0)*.07);if(b.atk)lines.push(`Ataque +${Math.round(b.atk*m)}`);if(b.slot==='arma')lines.push(`<span class="mut">Velocidade: ${SPEEDN(b.as||1)} (${(b.as||1).toFixed(2)}×) · dano por segundo ≈ ${Math.round(b.atk*m*(b.as||1)*10)/10}</span>`);if(b.two)lines.push('<span class="mut">Usa as duas mãos</span>');if(b.pierce)lines.push(`<span class="aff">Atravessa ${b.pierce} inimigo${b.pierce>1?'s':''}</span>`);if(b.heal)lines.push('<span class="aff">Transforma o Mago em Curandeiro</span>');if(b.dropOnly)lines.push('<span class="aff">★ Só cai de monstros: +30% de atributos</span>');if(b.def)lines.push(`Defesa +${Math.round(b.def*m)}`);for(const [a,v] of it.aff||[])lines.push(`<span class="aff">${AFF[a].f(v)}</span>`);if(b.lv>1)lines.push(`<span class="${P&&P.lv<b.lv?'bad':'mut'}">Requer nível ${b.lv}</span>`);if(b.cls&&P&&b.cls!==P.cls)lines.push('<span class="bad">Sua classe não pode usar</span>')}
  else{lines.push(`<span class="mut">${b.t==='use'?'Consumível':b.t==='quest'?'Item de missão':'Material'}</span>`)}
  if(b.t==='eq'){const cmp=compareHTML(it,esc);if(cmp)lines.push(cmp)}
  if(b.d)lines.push(esc(b.d));if(b.lore)lines.push(`<i class="lore">${esc(b.lore)}</i>`);if(extra)lines.push(`<span class="hint">${extra}</span>`);return lines.join('<br>')}
function showTip(html,ev){tip.innerHTML=html;tip.hidden=false;const r=tip.getBoundingClientRect();let x=ev.clientX+16,y=ev.clientY+12;if(x+r.width>innerWidth-8)x=ev.clientX-r.width-12;if(y+r.height>innerHeight-8)y=innerHeight-r.height-8;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px'}
const hideTip=()=>{tip.hidden=true};
function cell(it,onClick,extra,opt={}){const c=document.createElement('button');c.type='button';c.className='cell'+(opt.cls?' '+opt.cls:'');if(it){const b=BASES[it.id];c.innerHTML=`<img alt="" src="${iconURL(it.id)}">${it.n>1?`<span class="n">${it.n}</span>`:''}`;c.style.borderColor=b.t==='eq'&&(it.r||0)>0?RAR[it.r].c:'';c.setAttribute('aria-label',b.n);c.onmousemove=e=>showTip(itemTipHTML(it,typeof extra==='function'?extra(it):extra),e);c.onmouseleave=hideTip;c.onclick=e=>{hideTip();onClick&&onClick(it,e)}}else{c.classList.add('empty');if(opt.ph)c.innerHTML=`<span class="ph">${opt.ph}</span>`}return c}
// ---------- inventory ----------
function canEquip(it){const b=BASES[it.id];if(b.t!=='eq')return'Não é equipamento';if(b.cls&&b.cls!==P.cls)return`Apenas ${CLASSES[b.cls].n}`;if(b.lv>P.lv)return`Requer nível ${b.lv}`;return null}
function equipFromInv(i){const it=P.inv[i];const why=canEquip(it);if(why){toast('Não dá para equipar',why);sfx('no');return}const b=BASES[it.id],sl=b.slot;if(sl==='escudo'&&P.eq.arma&&BASES[P.eq.arma.id].two){toast('Mãos ocupadas','A arma atual usa as duas mãos');sfx('no');return}if(b.two&&P.eq.escudo){if(!addItem(P.eq.escudo)){toast('Inventário cheio','Libere espaço para a mão secundária');return}delete P.eq.escudo}const old=P.eq[sl];P.eq[sl]=it;P.inv[i]=old||null;refreshLook();sfx('equip');uiDirty=1}
function unequip(sl){const it=P.eq[sl];if(!it)return;if(!addItem(it)){toast('Inventário cheio');return}delete P.eq[sl];refreshLook();sfx('equip');uiDirty=1}
function invClick(i){const it=P.inv[i];if(!it)return;const b=BASES[it.id];
  if(shopKey){const pr=sellPrice(it)*(it.n||1);if(b.t==='quest'){toast('Item de missão','Não pode ser vendido');return}P.gold+=pr;P.inv[i]=null;log(`Vendeu ${b.n}${it.n>1?' ×'+it.n:''} por ${pr} ouro.`,'loot');sfx('coin');uiDirty=1;return}
  if(bankOpen){if(addItem(it,P.bank.items)){P.inv[i]=null;sfx('pick');uiDirty=1}else toast('Cofre cheio');return}
  if(b.t==='use')usePotion(it.id);else if(b.t==='eq')equipFromInv(i);else toast(b.n,b.t==='mat'?'Material: venda para a Lia ou guarde no banco':'Item de missão')}
function refreshInv(){const w=$('#invWin');if(w.hidden)return;const eg=$('#eqGrid');eg.innerHTML='';for(const [sl,lab] of SLOTS){const it=P.eq[sl];const c=cell(it,()=>unequip(sl),'Clique para remover',{ph:lab});c.classList.add('eqslot');const l=document.createElement('span');l.className='sl';l.textContent=lab;c.appendChild(l);eg.appendChild(c)}
  const g=$('#invGrid');g.innerHTML='';const ex=it=>shopKey?(BASES[it.id].t==='quest'?'Não pode ser vendido':`Clique para vender por ${sellPrice(it)*(it.n||1)} ouro`):bankOpen?'Clique para guardar no cofre':BASES[it.id].t==='eq'?'Clique para equipar':BASES[it.id].t==='use'?'Clique para usar':'';
  P.inv.forEach((it,i)=>g.appendChild(cell(it,()=>invClick(i),ex)));$('#goldT').textContent=P.gold.toLocaleString('pt-BR');
  const d=D();$('#invStats').textContent=`ATQ ${d.atk} · DEF ${d.def} · CRIT ${d.crit.toFixed(1)}% · VEL ${(d.speed/CFG.moveSpeed*100).toFixed(0)}%`}
// ---------- character ----------
function refreshChar(){const w=$('#charWin');if(w.hidden)return;const d=D(),body=$('#charBody');const c=CLASSES[P.cls];body.innerHTML='';
  const head=document.createElement('div');head.className='charhead';head.innerHTML=`<b></b><span class="mut"></span>`;head.querySelector('b').textContent=P.name+(P.title?` «${P.title}»`:'');head.querySelector('span').textContent=`${className(P)} · Nível ${P.lv} · ${P.pts} ponto(s) livre(s)`;body.appendChild(head);
  const g=document.createElement('div');g.className='stats';for(const k of ['for','des','int','vit']){const a=document.createElement('span');a.innerHTML=`${STATN[k]}${k===c.main?' <em>principal</em>':''}`;const v=document.createElement('b');v.textContent=d.s[k]+(d.s[k]!==P.st[k]?` (${P.st[k]})`:'');const bt=document.createElement('button');bt.type='button';bt.className='btn sm';bt.textContent='+';bt.disabled=P.pts<=0;bt.setAttribute('aria-label','Aumentar '+STATN[k]);bt.onclick=()=>{if(P.pts>0){P.pts--;P.st[k]++;sfx('ok');uiDirty=1}};g.append(a,v,bt)}body.appendChild(g);
  const dv=document.createElement('div');dv.className='derived';for(const [l,v] of [['Ataque',d.atk],['Defesa',d.def],['HP máx.',d.maxHp],['Mana máx.',d.maxMp],['Crítico',d.crit.toFixed(1)+'%'],['Vel. ataque',(d.aspd*100).toFixed(0)+'%'],['Esquiva',d.dodge.toFixed(1)+'%'],['Movimento',(d.speed/CFG.moveSpeed*100).toFixed(0)+'%']]){const e=document.createElement('div');e.innerHTML=`<span>${l}</span><b>${v}</b>`;dv.appendChild(e)}body.appendChild(dv);
  body.appendChild(skillsPanel())}
// ---------- quests ----------
const QTXT={filho:{t:'O Filho do Ferreiro',s:['','Encontre Tomé, filho de Bruno. Goblins foram vistos depois do rio, a sudeste.','Tomé está livre. Fale com Bruno na forja de Pedravale.','Concluída. Bruno agora vende o estoque do mestre.']},
  cacada:{t:'A Última Caçada',s:['','Cace o Lobo Alfa no Bosque de Vellmor e leve a pele para Ilsa. Ele raramente aparece; ouça os uivos.','Concluída. A caçada de Ilsa terminou.']},
  porta:{t:'A Porta Selada',s:['','Uma porta sob o templo, com um crânio no lugar da fechadura. Algo na cripta deve abri-la.','Concluída. O Abade e o Rei Goblin estavam aliados.']},
  santuario:{t:'As Pedras do Bosque',s:['','Uma página fala de quatro flores-lume em volta das pedras antigas do Bosque de Vellmor. Acenda todas de uma vez, à noite.','O círculo se abriu. Algo antigo espera no Santuário Lunar.','Concluída. O Ancião Lunar descansa.']},
  tumulo:{t:'O Túmulo Sem Nome',s:['','Uma lápide sem nome no cemitério. Algo pode despertar quando a vila dormir.','O Guardião Esquecido despertou no cemitério.','Concluída. O Guardião descansa.']}};
for(const id in RQ)QTXT[id]=rqTxt(id);
const qs=(q,st)=>typeof q.s[st]==='function'?q.s[st]():q.s[st];
function refreshQuests(){const w=$('#questWin');if(w.hidden)return;const body=$('#questBody');body.innerHTML='';let any=0;for(const k in QTXT){const st=P.q[k];if(!st)continue;any=1;const q=QTXT[k],e=document.createElement('div');e.className='qrow'+(st>=q.s.length-1?' done':'');e.innerHTML='<b></b><p></p>';e.querySelector('b').textContent=q.t;e.querySelector('p').textContent=qs(q,st);body.appendChild(e)}
  if(!any){body.innerHTML='<p class="mut">Nenhuma missão ainda. Converse com os moradores de Pedravale e explore o mundo. Algumas histórias só aparecem para quem procura.</p>'}}
function questTracker(){const el=$('#qTrack');const rows=[];if(EV.cur){const t=Math.max(0,Math.ceil(EV.cur.t));rows.push(['★ '+EV.cur.title,`${EV.cur.desc} · ${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`])}for(const k in QTXT){const st=P.q[k],q=QTXT[k];if(st&&st<q.s.length-1)rows.push([q.t,qs(q,st)])}el.hidden=!rows.length;if(!rows.length)return;const html=rows.map(([t,s])=>`<div><b>${t}</b><span>${s}</span></div>`).join('');if(el._h!==html){el._h=html;el.querySelector('.body').innerHTML=html}}
// ---------- shop & bank ----------
let shopAt=null;function openShop(key,name){shopKey=key;shopAt=[P.x,P.y,P.map];bankOpen=false;hideWin('#bankWin');$('#shopTitle').textContent=name;renderShop();showWin('#shopWin');showWin('#invWin');uiDirty=1}
function renderShop(){if(!shopKey)return;const body=$('#shopBody');body.innerHTML='';const list=shopKey==='brunoMestre'?SHOP.bruno.concat(SHOP.brunoMestre):SHOP[shopKey];
  for(const id of list){const b=BASES[id],r=document.createElement('div');r.className='shoprow';const lock=b.cls&&b.cls!==P.cls;r.innerHTML=`<img alt="" src="${iconURL(id)}"><div class="nm"><b></b><span class="mut"></span></div><div class="acts"></div>`;r.querySelector('b').textContent=b.n;r.querySelector('.mut').textContent=`${b.buy} ouro${b.cls?' · '+CLASSES[b.cls].n:''}${b.lv>1?' · nv '+b.lv:''}`;if(lock)r.classList.add('dim');
    r.querySelector('img').onmousemove=e=>showTip(itemTipHTML({id,r:0,aff:(b.fix||[]).map(a=>a.slice())}),e);r.querySelector('img').onmouseleave=hideTip;
    for(const q of b.t==='use'?[1,5]:[1]){const bt=document.createElement('button');bt.type='button';bt.className='btn sm';bt.textContent=q>1?'×'+q:'Comprar';bt.disabled=P.gold<b.buy*q;bt.onclick=()=>{if(P.gold<b.buy*q)return;let ok=true;for(let i=0;i<q;i++){if(!addItem(makeItem(id,0))){ok=false;break}P.gold-=b.buy}if(!ok)toast('Inventário cheio');sfx('coin');uiDirty=1};r.querySelector('.acts').appendChild(bt)}body.appendChild(r)}
  const h=document.createElement('p');h.className='hint';h.textContent='Para vender, clique nos itens do seu inventário.';body.appendChild(h)}
function openBank(){bankOpen=true;shopAt=[P.x,P.y,P.map];shopKey=null;hideWin('#shopWin');showWin('#bankWin');showWin('#invWin');uiDirty=1}
function refreshBank(){if($('#bankWin').hidden)return;const g=$('#bankGrid');g.innerHTML='';P.bank.items.forEach((it,i)=>g.appendChild(cell(it,()=>{if(addItem(it)){P.bank.items[i]=null;sfx('pick');uiDirty=1}else toast('Inventário cheio')},'Clique para retirar')));$('#bankGold').textContent=P.bank.gold.toLocaleString('pt-BR')}
$('#bDep').onclick=()=>{const v=Math.min(P.gold,100);P.gold-=v;P.bank.gold+=v;uiDirty=1;sfx('coin')};$('#bDepAll').onclick=()=>{P.bank.gold+=P.gold;P.gold=0;uiDirty=1;sfx('coin')};
$('#bWd').onclick=()=>{const v=Math.min(P.bank.gold,100);P.bank.gold-=v;P.gold+=v;uiDirty=1;sfx('coin')};$('#bWdAll').onclick=()=>{P.gold+=P.bank.gold;P.bank.gold=0;uiDirty=1;sfx('coin')};
// ---------- action bar ----------
const SKICON={};
let barSet='';function buildActionBar(){barSet=barSig();for(const c of ['g','a','m','l','h',...Object.keys(EVO)])for(const k of ['atk','Q','E','R','T','G','dash'])if(k!=='G'||EVO[c])SKICON[c+k]=k==='dash'&&EVO[c]?skillIcon(EVO[c].cls,'dash'):skillIcon(c,k);const bar=$('#actionbar');bar.innerHTML='';
  syncIcons();const slots=[['atk','Mouse',SKICON[setCode(P)+'atk'],skillSet(P).atk.n],['dash','Esp',SKICON[setCode(P)+'dash'],'Dash: avanço rápido com invencibilidade curta'],...skKeys(P).map(k=>[k,k,SKICON[setCode(P)+k],`${skillSet(P)[k].n} (${skillSet(P)[k].mp} mana): ${skillSet(P)[k].d}`]),['sep'],...[['pot_hp1','1'],['pot_hp2','2'],['pot_mp','3'],['scroll','4']].map(([id,k])=>[id,k,iconURL(id),BASES[id].n+': '+BASES[id].d])];
  for(const s of slots){if(s[0]==='sep'){const d=document.createElement('span');d.className='sep';bar.appendChild(d);continue}const [id,key,img,title]=s;const e=document.createElement('button');e.type='button';e.className='slot';e.dataset.id=id;e.title=title;e.setAttribute('aria-label',title);e.innerHTML=`<img alt="" src="${img}"><span class="k">${key}</span><span class="n"></span><span class="cd"></span><span class="lk"></span>`;
    e.addEventListener('pointerdown',ev=>{ev.preventDefault();initAudio();if(id==='atk'){input.mdown=true;const up=()=>{input.mdown=false;removeEventListener('pointerup',up)};addEventListener('pointerup',up)}else if(id==='dash')doDash();else if(skillSet(P)[id])useSkill(id);else usePotion(id)});bar.appendChild(e)}}
function updActionBar(){const d=D();updTouch();for(const e of $('#actionbar').children){const id=e.dataset.id;if(!id)continue;const cd=e.querySelector('.cd'),n=e.querySelector('.n'),lk=e.querySelector('.lk');
  if(id==='atk'){cd.style.height='0'}else if(id==='dash'){cd.style.height=(P.cds.dash/CFG.dashCD*100)+'%'}else if(skillSet(P)[id]){const s=skillSet(P)[id];cd.style.height=(P.cds[id]/(s.cd*CFG.skillCD)*100)+'%';const locked=P.lv<s.lv;e.classList.toggle('lock',locked);lk.textContent=locked?'Nv'+s.lv:'';e.classList.toggle('nomana',!locked&&P.mp<s.mp)}
  else{const c=countItem(id);n.textContent=c;e.classList.toggle('lock',!c);cd.style.height=id==='scroll'?'0':(P.cds.pot/CFG.potCD*100)+'%'}}}
// ---------- HUD ----------
function updHud(){const d=D();updPartyBox();{const ni=$('#netInfo');if(ni){const on=NET&&netState!=='off';ni.hidden=!on;if(on){const n=netCount();ni.textContent=netState==='on'?`● Online · ${n?n+' amigo'+(n>1?'s':'')+' aqui':'só você por enquanto'}`:'○ Reconectando...';ni.dataset.on=netState==='on'?1:0}}}$('#cName').textContent=P.name;$('#cLv').textContent=`${className(P)} · Nv ${P.lv}`;
  $('#hpB').style.width=(P.hp/d.maxHp*100)+'%';$('#hpT').textContent=`${Math.ceil(P.hp)} / ${d.maxHp}`;$('#mpB').style.width=(P.mp/d.maxMp*100)+'%';$('#mpT').textContent=`${Math.floor(P.mp)} / ${d.maxMp}`;
  const nx=need(P.lv);$('#xpB').style.width=(P.exp/nx*100)+'%';$('#xpT').textContent=`Nível ${P.lv} · ${P.exp} / ${nx} XP (${(P.exp/nx*100).toFixed(1)}%)`;$('#hudGold').textContent=P.gold.toLocaleString('pt-BR');
  const hrs=TIME*24,h=Math.floor(hrs),mi=Math.floor((hrs-h)*60);$('#clock').textContent=M.indoor?'Subterrâneo':`${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')} · ${isNight()?'Noite':sunLevel()<.45?'Crepúsculo':'Dia'}${weather.rain>.3&&M.id==='world'?' · Chuva':''}`;$('#clock').dataset.n=isNight()?1:0;
  $('#ptsBadge').hidden=!P.pts;$('#ptsBadge').textContent=P.pts;
  const it=nearestInteract(),pr=$('#prompt');if(it&&!P.dead){pr.hidden=false;pr.querySelector('span').textContent=it.label}else pr.hidden=true;
  const bb=$('#bossbar');if(bossActive&&!bossActive.dying&&bossActive.m===M.id){bb.hidden=false;$('#bossbar .nm').textContent=bossActive.def.n;$('#bossB').style.width=(bossActive.hp/bossActive.maxHp*100)+'%';$('#bossT').textContent=`${Math.ceil(bossActive.hp)} / ${bossActive.maxHp}`}else bb.hidden=true;
  if((shopKey||bankOpen)&&shopAt&&(shopAt[2]!==P.map||Math.hypot(P.x-shopAt[0],P.y-shopAt[1])>4)){hideWin('#shopWin');hideWin('#bankWin');uiDirty=1}
  if(barSet!==barSig())buildActionBar();updActionBar();questTracker();drawMini();drawPortrait();
  if(uiDirty){uiDirty=0;refreshInv();refreshChar();refreshQuests();refreshBank();if(shopKey)renderShop()}}
// ---------- minimap & portrait ----------
const mini=$('#mini'),mc=mini.getContext('2d');const MINI={};
function miniImg(m){if(MINI[m.id])return MINI[m.id];const [c,x]=mk(m.w,m.h);const col={[GRASS]:'#5a8a3e',[DIRT]:'#a8865a',[COBBLE]:'#a8a4ac',[WATER]:'#3a74a6',[SAND]:'#d8c48e',[FOREST]:'#3a6634',[FIELD]:'#c4a84e',[BRIDGE]:'#8a5a34',[CAVE]:'#5a4a3a',11:'#6a6a7a',12:'#1e3a3c',[VOID]:'#0b0a10',[GRAVE]:'#4e6a4a',...MINI_EXTRA};for(let y=0;y<m.h;y++)for(let i=0;i<m.w;i++){const t=m.terr[y*m.w+i];x.fillStyle=m.solid[y*m.w+i]&&t!==WATER&&t!==VOID?(t===CAVE?'#2a1e24':'#2a3a22'):col[t]||'#000';x.fillRect(i,y,1,1)}return MINI[m.id]=c}
function drawMini(){const r=mini.getBoundingClientRect();const w=Math.round(r.width*DPR),h=Math.round(r.height*DPR);if(!w)return;if(mini.width!==w){mini.width=w;mini.height=h}mc.setTransform(1,0,0,1,0,0);mc.fillStyle='#0b0a10';mc.fillRect(0,0,w,h);
  const span=26,s=w/(span*1.414),a=s*.707,bb=s*.3535,cx=P.x,cy=P.y;mc.imageSmoothingEnabled=false;mc.setTransform(a,bb,-a,bb,w/2-a*cx+a*cy,h/2-bb*cx-bb*cy);mc.drawImage(miniImg(M),0,0);mc.setTransform(1,0,0,1,0,0);
  const pt=(x,y)=>[a*(x-cx)-a*(y-cy)+w/2,bb*(x-cx)+bb*(y-cy)+h/2];const dot=(x,y,c,sz)=>{const [px,py]=pt(x,y);if(px<0||py<0||px>w||py>h)return;mc.fillStyle='#000';mc.fillRect(Math.round(px-sz/2)-1,Math.round(py-sz/2)-1,sz+2,sz+2);mc.fillStyle=c;mc.fillRect(Math.round(px-sz/2),Math.round(py-sz/2),sz,sz)};
  for(const n of npcs)if(n.m===M.id&&!n.hidden&&!n.indoor)dot(n.x,n.y,'#f2c14e',2*DPR);if(M.id==='world')for(const b2 of bots)dot(b2.x,b2.y,'#7ab4ff',2*DPR);for(const r of remotes.values())if(r.m===M.id)dot(r.x,r.y,party&&r.pt===party?'#ffd86a':'#7af0b0',3*DPR);for(const m of mobs)if(m.m===M.id&&!m.dying&&m.def.ai!=='dummy'&&dist(m,P)<12)dot(m.x,m.y,m.def.boss?'#ff3a2a':'#d8584a',(m.def.boss?3:2)*DPR);if(EV.cur&&EV.cur.mob&&EV.cur.map===M.id&&!EV.cur.mob.dying&&!EV.cur.mob.dead){const g=EV.cur.mob,s2=(4+Math.sin(T*6)*1.5)*DPR;dot(g.x,g.y,'#ffd23a',Math.round(s2))}if(pet&&pet.m===M.id)dot(pet.x,pet.y,'#c8a0ff',2*DPR);dot(P.x,P.y,'#ffffff',3*DPR)}
const portrait=$('#portrait'),pc=portrait.getContext('2d');let portraitKey='';
function drawPortrait(){const k=lookKey(P.look)+(P.look.sprite&&sprReady(P.look.sprite)?'s':'');if(k===portraitKey)return;portraitKey=k;const fr=P.look.sprite&&sprReady(P.look.sprite)?SPR[P.look.sprite].frames.idle[0][0][0]:charFrame(P.look,0,'idle',0);pc.imageSmoothingEnabled=false;pc.clearRect(0,0,portrait.width,portrait.height);const sc=3;pc.drawImage(fr.cv,portrait.width/2-fr.ax*sc,portrait.height+12-fr.ay*sc*.55-28,fr.cv.width*sc,fr.cv.height*sc)}
// ---------- chat ----------
$('#chatform').addEventListener('submit',e=>{e.preventDefault();const inp=$('#chatin'),t=inp.value.trim();inp.value='';inp.blur();if(!t||!P)return;if(t[0]==='/'){partyCmd(t);return}log(`${P.name}: ${t}`,'me');say(P,t,4.5);netChat(t);const lt=t.toLowerCase();
  if(/(^|\s)(oi|ola|olá|eae|eai|salve|opa|bom dia|boa tarde|boa noite)(\s|$|!)/.test(lt))later(rnd(1,2.5),()=>botSay(pick(bots),pick(['oi!','eae '+P.name,'salve','bem-vindo a Pedravale'])));
  else if(/\b(pt|party|grupo)\b/.test(lt))later(rnd(1.2,3),()=>botSay(pick(bots),pick(['bora! mas tô longe kkk','tô solo agora, foi mal','depois do Chefe Goblin eu topo'])));
  else if(/(ajuda|como|onde)/.test(lt))later(rnd(1.2,3),()=>botSay(pick(bots),pick(['fala com os npcs da vila, eles dão as dicas','espaço é o dash, salva vida','o banco do Osvaldo guarda seus itens'])))});
